(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Assignment_4_atlas_1", frames: [[0,0,661,566],[0,568,661,566],[1220,321,52,55],[1039,286,179,112],[1225,0,177,319],[899,286,138,151],[899,0,324,284],[0,1136,609,491],[611,1136,621,395],[663,0,234,678]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_1 = function() {
	this.initialize(img.CachedBmp_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,3341,2154);


(lib.Background = function() {
	this.initialize(img.Background);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,4200,3000);


(lib.Dumbellpng复制 = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Dumbellpng复制2 = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.face = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.Ghosts = function() {
	this.initialize(img.Ghosts);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,4028,2813);


(lib.Lowerarm = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.People = function() {
	this.initialize(img.People);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,4200,3000);


(lib.Rotationgirl = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.Scaryghost = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.Scorepannel = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.Swimer3 = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();



(lib.Swimmer2 = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(8);
}).prototype = p = new cjs.Sprite();



(lib.Volleyballgirlpng复制 = function() {
	this.initialize(ss["Assignment_4_atlas_1"]);
	this.gotoAndStop(9);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.winner_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0033").s().p("EhYeAc0QiGhOhAiDQgghBgQhTQgNhDgFhZQgDhJAGgzQAHhDAZgyQA0htCShIQAzgZBSgfICHgxQC7hJCdh8QBEg3AbguQAig9gDhYQgDg5gXhjIkMx7QhZGkjMF4QgzgPhMACQhXAFgrgBQhJAAg4gVQhDgageg0QgTghgFgwQgDgdACg6IA11aQACgyAXgmQAagrAlANQArAPgCBWIgxXXQA9A9BigOQBdgMBBhDQA3g5AkhcQAXg7AbhxIBJkqQArixAehaQAyiSBEhmQAZglAXgGQAZgHAXATQAXARAHAbQAFAWgDAeQgCAOgIAmQgtDOAZD0QATC4BFEJQAnCWBSEuQBBEGAODCQGQibFTkFQieing+jnQg+jnA2jgQAbhyA6gwQArgkBGgJQAygHBNAHQBrAJBGASQBfAXBDAuQBNA0AkBUQAnBagcBQQgMAigkBDQgbA8APApQCImADvlJQAegpAhgTQApgYAgATQAlAXgBBNQAAApgFBTQgCBJAIAxQALBKAwBrQBCCUAKAbQAWA+AYBtQAeCHALAnQA4DHB1BOIBBgNQBAhfAwiEQAfhWAsihQAviuAahKQAuiJA7hhQAgg1AjADQAmADAWBEIBrFJQBVEIBOCKQB1DQCqBXQAmAUASARQAbAagGAbQgGAageALQgaAKgggDQjEgXihkcQiokphNlLQg6AegZBTQgIAdgTB7QgMBQggBfQgUA8gtBsQglBcghAxQgxBIhAAZQhTAghdguQhWgrgzhWQgnhDgbhpQgch6gPg9QgThJgjhkIg+irQhJjSgKiMQhUBahICyIg6CTQgjBWgfA5QhgCxjACiQh5Blj4ChQihBphYAzQiMBSh6AxQhDAagbAPQgyAcgWAnQgPAZgGAjQgEAZAAAoQgCBHAFCjQAECYgDBSQgKEOhjCnQhMB/iBBPQiEBQiRADIgPAAQiMAAh+hKgEhQ6ANDQhNAsibA4QilA8hGAkQhhAygdA+QgNAbgEAkQgDAVgBAsQgCBQADAnQAEBCARAyQAWBAAwA6QAsA0A9AqQB8BUB2gIQBqgGBfhQQBRhEA+huQAnhGATg9QARg1AHhDQAFgvADhLQAKkNgXkLQhmCCiQBQgEg/bgOFQg4ANgcAkQg2CVAMCjQAMCjBLCMQAhA8AkAaQAXAQAcAEQAdAFAYgNQAUgKAagiQAyg/AdguQAng+AUg6QAGgRAPg1QAMgsALgZQAGgQAVgnQASgiAIgVQALgfgBgdQgCghgRgXQgPgVgigRQgogSgTgKIgngZQgXgPgQgHQgYgLghgEQgUgCgogBIgNAAQg4AAgiAHgEBdZAIAQgVgGgUgOQgagTgigxQhqiWhGirQgLgdgEgUQgFgcAJgUQAHgPAQgLQAPgLASgBQAfAHAZAcQAVAYAOAlIAXBCQANAnAPAYQAJANAeAjQAZAdAKAVIALAdQAGASAHAKQAHALATAQQATAQAHAKQATAZgFAiQgEAhgZATQgKADgLAAQgLAAgNgDgABEE+QgsAEgWABQgkACgdgJQgjgMgNgbQgJgTABggQADgjgBgSQgBgkgXgzIglhVQgTg2AAhUQAEhfgDgwQgCgvgNhLQgQhegDgbQgGg1gChBQgBgoABhPIABjUQAAhSApgRQAVgIAXALQAWALAMAWQAKATADAaQACAQgBAfIgEDKQgBB1AMBUIARBfQALA7ACAlQACAYgDByQgCBUANAzQAGAYAkBXQAbBEABAuQAAAQAHAMQAJAOAKgHQgIg6AdgzQAGgKAWggQATgZAHgRQANgigFhNQgFhMAQgiQAIgRAZggQAXgfAHgTQAJgYgDguQgCgzAEgVQAEgPAPghQAOgfADgSQABgKAAggQAAgbAFgPQAJgaAcgRQAZgPAggEQBDgJA/AlQA/AkAaA/QAGAOAJAfQAIAeAHAPQAHARAUAhQAUAgAHATQAGAQAKAqQAJAlAJAUQAaA1BUAsQB0A8AUARQAQANAcAdQAdAdAPANQAwAlA+ANQA+ANA6gSQAIg7gJiuQgHiTAahTQAEgNAhhRQAXg4AEgnQACgVgDg4QgDgxAGgcQAEgQALgeQAMgfADgPQADgNAEglQADggAGgRQAOgpAogjQAbgXA2gfQAfAJAUAdQAUAdgCAgQgCAhgYAaQgYAaghAEQAIAmgTA6QgaBQgCARQgEAZADA0QACA0gEAaQgFAfgUAsQgbA+gEAMQgSAygFBCQgDApACBOIAEDgQACBmgzATQgOAFgegBIi5gGQgngCgQgEQglgJgqgiQgVgRg3g1QgvgsgggVQgSgMhPgoQg9gfgegeQgbgbgXgrQgNgagWg2IhPjFQgOgkgLgUQgRgdgWgQQgqBYgKBhIgGA9QgEAjgKAYQgHASgZAmQgWAjgHAVQgKAgAEBKQAFBEgPAiQgHARgXAgQgXAegHASQgIATgGBVQgFBAgfAXQgagKgmACgEBJjADMIhXgGQgUgBgMgEQgOgGgUgYQhOhbgpg3QgdglgDgaQgCgTAKgQQAKgSARgDIAQgCQAJgDABgGQAcACAbAZQASAQAXAiIAkA1QARAZAMAJQAOAJAWADIAmAEQAbADAUANQAXAPAEAXQADAVgUAiQgLAUgLAFQgHADgMAAIgIAAgEBQMABQQgggCgQgMQgHgFgJgNQgKgOgGgFQgPgOgxgJQgtgIgNgUQgIgMAAgQQABgQAJgMQAIgMAOgHQAOgHAPAAIAAgKQAzgIA3AaQAvAXAsArQAVAVAGAPQALAagMASIgPARQgJAKABAIQgMgEgngBgEA7WgAEIgYgBQgNgBgJgEQgNgGgNgMIgWgYQgSgVg3gxQgwgrgXgeQgVgcgeg5Qggg9gMgbIgdhDQgSgqgNgZIghg6QgUgkgLgWQgTgrgOg9IgThtQgGghgHgSQgLgbgUgNQgagSgnAHQgjAGgkAZQgYARglAkQhHBFgpAuQg7BDglA+QgWAmgcA+QhNCsgsC0QgYgFgnAAIhAgCQhLgEgggmQgcgggBg9QAEhHAAgjQgBgsgRhHQgVhWgEgeQgDgdgBhTQAAhGgJgpIgjgBIjnJcQgaBEgQAiQgZA3gcAoQghACgVgDQgdgGgOgSQgJgNgEgUQgCgMAAgXIADmcQAAhwAJg8QAOhfAphBQAWghAggQQAlgTAaAUQAQAMAFAWQAFAUgFAVQgEARgLAVIgTAlQgjBHgFBiQgDA+AJB0IDMoLQAhhTAugBQAYgBAZAUQAPAMAbAbIAvAlQAcAWAMAUQAUAjgFA7IgKBmQABApAXBLQAYBOADAlQACAhgFBCQAAA7AVAhQAVgFAIgdIAJg0QAFgcAVglIAkg/QAKgUAPgsQAOgrALgVQAMgVAZgiQAcgmAKgQIAagxQAQgeAMgRQARgZAWgQQAZgRAagCQABhCBxgwQBVglA4gJQBQgOA4AiQA1AgAdBNQALAcAbBzQATBQAfBKQAuBvBHBaIAaAiQAOATAHARQAEALAFAUIAHAfQAPAuAsArQAdAbA7AoQAVAPATAEQAYAFANgOQgJgRACgVQADgUANgPQANgOATgFQAUgEATAHQAhANALArQAJAhgEAwQgCAYgFAPQgGAVgOALQgMAKgUAEQgNACgYAAgEBbggGUQgZgLgOgYQgMgUgDgdQgCgRAAgkIAGpuQAAhKgCglQgEg+gOgwIgOgrQgHgZgBgTQgBgYAKgVQAKgWAUgJQAVgJAZAKQAXAJAPAUQANASAHAaQAEARAFAfQAQB5AECYQACBcgBC3IgDFMQgBAwgEAZQgGAogSAbQgMAGgNAAQgLAAgNgFgEBPrgIqQgQgSAAguIAAsdQggABgXgcQgXgbAHggQAHghAkgRQAjgRAjAMQAgALAXAeQAWAbAKAlQAIAeAAAoIgCBHQgHCJABCxIAFE7QAAAlgCAUQgFAggOAVQgRAYgeAHIgPABQgWAAgNgPgEBG7gMZQgXgGgPgTQgMgQgIgZQgEgQgFgdQgNhTgFgsQgMhxgBiPQgBhWAFirQgagGgVgQQgXgRgJgYQgJgZAIgbQAJgbAWgNQAcgPAnALQAkAMAbAgQAZAeANAoQAKAiADAsQABAbgBA1IgGDuQgCBDAIAkQAGAaATAzQASA4gEA3QgEA8gdAtQgMAHgOAAQgIAAgKgDgEAgQgTrQgbAAgMgIQgRgLgFgeQgDgjgEgQQgIgjgkgfQgIgIg7gqQgpgdgtgrQgbgagzg3QgQgRgGgJQgLgQgEgPQgEgSAIgQQAJgSAQgDIAVgFQALgDgBgJQAvAWA9A5QBOBLAXAQQAHAGA1AhQAkAYAUAUQAwAwAKBHQAKBIghA8QgLgGgdAAg");
	this.shape.setTransform(1110.079,565.6352);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF99").s().p("EibqBblMAAAi3JME3VAAAMAAAC3JgEg8CgADQAXBiACA5QADBYgiA9QgbAuhEA3QicB8i8BJIiHAxQhSAfgzAZQiSBIg0BtQgZAygHBDQgGAzAEBJQAEBZANBDQAQBTAgBBQBACDCGBOQCFBOCUgEQCRgDCEhQQCBhPBMh/QBjinAKkOQADhSgEiYQgEijABhHQABgoADgZQAHgjAOgZQAXgnAxgcQAbgPBEgaQB5gxCMhSQBYgzCihoQD4ihB5hmQDAiiBgixQAfg5AihWIA6iTQBJiyBThaQAKCMBJDSIA+CrQAkBkASBJQAPA9AcB6QAbBqAnBDQAzBWBWAqQBdAuBTggQBBgZAwhHQAhgxAlhdQAthsAUg8QAhhfALhQQATh7AIgdQAahTA5geQBNFLCoEqQChEbDEAXQAhADAZgKQAegLAGgaQAHgbgcgaQgRgRgngTQiqhXh1jRQhOiKhVkIIhrlJQgWhEgmgDQgjgDggA1Qg7BhguCJQgZBKgwCuQgsChgfBWQgwCFhABfIhBANQh1hOg4jIQgLgngeiHQgYhtgWg+QgKgbhCiUQgwhrgLhKQgIgxADhJQAEhTAAgpQABhNglgXQgggTgpAYQghATgeApQjvFJiHGAQgQgpAbg8QAkhDAMgiQAdhQgohaQgkhUhNg0QhCguhfgXQhHgShqgJQhOgHgyAHQhFAJgsAkQg6AwgbByQg2DgA/DnQA9DnCeCoQlTEEmQCbQgOjChBkGQhRkugniWQhGkJgTi4QgZj0AtjOQAIgmACgOQADgegFgWQgHgbgWgRQgYgTgZAHQgXAGgZAlQhEBmgxCSQgfBagrCxIhIEqQgcBxgXA7QgkBcg3A5QhBBDhcAMQhjAOg8g9IAw3XQAChWgqgPQgmgNgaArQgXAmgCAyIg1VaQgCA6ADAdQAFAwAUAhQAdA0BDAaQA4AVBJAAQArABBXgFQBNgCAyAPQDMl4BZmkgEBrCgDhQgQALgGAQQgJAUAEAcQAEAUAMAdQBFCqBqCWQAiAxAaATQAUAOAWAGQAXAGAWgGQAYgTAFghQAEgigTgZQgGgKgUgQQgTgQgHgLQgHgKgGgSIgLgdQgJgVgagdQgegjgIgMQgQgYgNgnIgWhCQgPglgVgYQgYgdgggHQgRABgQALgAT2B5QAggXAEhAQAHhUAHgTQAHgSAXgeQAXggAHgRQAPgigFhFQgEhKAKggQAHgVAWgjQAZgmAIgSQAKgYADgjIAGg9QAKhhArhYQAVAQARAdQALAUAOAkIBPDFQAWA2AOAaQAWArAbAbQAeAeA9AfQBPAoASAMQAgAVAvAtQA3A1AVARQAqAiAlAJQAQAEAnACIC6AGQAdABAOgFQAzgTgChmIgEjhQgBhOADgpQAEhCASgyQAEgMAcg+QATgsAFgfQAFgagDg0QgCg0ADgZQACgRAahQQATg6gIgmQAhgEAYgaQAYgaACghQADgggVgdQgTgdgggJQg2AfgaAXQgpAjgNApQgHARgCAgQgFAlgDANQgDAPgMAfQgLAegDAQQgHAcADAxQAEA4gDAVQgEAngXA4QggBRgFANQgaBTAHCTQAJCugIA8Qg6ASg+gNQg+gNgvgmQgQgNgcgdQgdgdgPgNQgVgRhzg8QhUgsgag1QgKgUgIglQgKgqgHgQQgHgTgTggQgVghgHgRQgHgPgIgeQgJgfgFgOQgbg/g+gkQg/glhEAJQggAEgYAPQgdARgIAaQgGAPAAAbQAAAggBAKQgDASgOAfQgPAhgEAPQgEAVADAzQACAugJAYQgGATgYAfQgZAggIARQgPAiAEBMQAFBNgNAiQgHASgTAZQgWAggGAKQgdAzAJA6QgLAHgIgOQgIgMAAgQQgBgugchEQgkhYgGgYQgNgzAChUQADhygBgYQgDglgLg7IgQhfQgNhUABh1IAFjKQAAgfgCgQQgDgagKgTQgLgWgXgLQgWgLgVAIQgqARAABSIgBDUQgBBPACAoQABBBAHA1QADAbAQBeQAMBLADAvQACAwgEBfQABBUASA3IAmBVQAWAzABAkQABASgDAiQgBAgAKATQANAbAiAMQAdAJAmgCQAVgBAtgEIAKAAQAfAAAWAIgEBXYgE1IgPACQgSADgKASQgKAQADATQACAaAdAmQApA3BOBbQAUAYAOAGQAMAEAVABIBWAGQATAAAIgDQALgFALgUQAUgigDgVQgEgXgWgPQgVgNgagDIgngEQgWgDgOgJQgMgJgRgZIgkg2QgXgigSgQQgbgZgcgCQgBAGgJADgEBfpgE/IAAAKQgPAAgNAHQgPAHgIAMQgJAMgBAQQAAAQAIAMQAOAUAsAJQAxAJAQAOQAFAFAKAOQAKANAGAFQAQAMAgACQAnABAMAEQgBgIAJgKIAPgRQAMgSgLgaQgGgQgVgVQgsgrgugXQgrgUgnAAQgNAAgMACgEBEfgRnQAUANALAbQAHASAGAhIAUBtQANA9AUArQAKAWAUAkIAhA6QANAZASAqIAdBDQAMAbAgA9QAeA5AVAcQAXAeAwArQA3AxATAVIAVAYQANAMANAGQAJAEAOABIAXABIB6ACQAZAAAMgCQAUgEANgKQANgLAHgVQAEgPADgYQAEgwgKghQgLgrghgNQgTgHgTAEQgUAFgNAOQgNAPgDAUQgCAVAJARQgNAOgYgFQgSgEgWgPQg7gogdgbQgsgrgPguIgHgfQgFgUgEgLQgHgRgOgTIgagiQhHhaguhvQgfhKgThQQgbhzgKgcQgehNg1ggQg3gihRAOQg4AJhVAlQhxAwgBBCQgaACgZARQgVAQgSAZQgMARgPAeIgbAxQgKAQgcAmQgZAigLAVQgMAVgOArQgPAsgKAUIgkA/QgVAlgFAcIgJA0QgIAdgVAFQgVghABg7QAEhCgCghQgDglgYhOQgXhLgBgpIALhmQAFg7gVgjQgMgUgcgWIgvglQgbgbgPgMQgZgUgYABQguABghBTIjLILQgKh0ADg+QAFhiAjhHIATglQALgVAEgRQAFgVgFgUQgFgWgPgMQgbgUgkATQghAQgVAhQgpBBgOBfQgKA8AABwIgDGcQABAXACAMQADAUAJANQAPASAdAGQAUADAhgCQAcgoAag3QAPgiAahEIDnpcIAjABQAJApABBGQAABTADAdQAEAeAVBWQASBHAAAsQAAAjgEBHQABA9AcAgQAgAmBMAEIA/ACQAnAAAZAFQAri0BNisQAcg+AWgmQAmg+A6hDQApguBHhFQAlgkAZgRQAkgZAjgGQAKgCAKAAQAZAAATANgEBsdgbYQgTAJgLAWQgJAVABAYQAAATAIAZIANArQAOAwAEA+QACAlAABKIgGJuQAAAkACARQADAdAMAUQAOAYAZALQAbALAWgMQASgbAGgoQAFgZAAgwIADlMQACi3gDhcQgEiYgQh5QgEgfgFgRQgHgagMgSQgQgUgXgJQgMgFgMAAQgLAAgLAEgEBhNgM3QAAAuAQASQASAUAggGQAegHASgYQAOgVAEggQACgUAAglIgFk7QgBixAHiJIAChHQAAgogIgeQgJglgXgbQgXgegggLQgigMgkARQgkARgHAhQgHAgAXAbQAXAcAggBgEBWfgdwQgXANgJAbQgIAbAJAZQAKAYAWARQAVAQAaAGQgFCrABBWQABCPAMBxQAFAsANBTQAFAdAEAQQAIAZAMAQQAQATAXAGQAZAIASgMQAdgtAEg8QAFg3gSg4QgUgzgGgaQgIgkAChDIAGjuQABg1gBgbQgCgsgLgiQgNgogZgeQgbgggkgMQgQgFgPAAQgTAAgQAJgEAs4geeIgUAFQgRADgIASQgJAQAFASQADAPALAQQAGAJARARQAyA3AbAaQAuArAoAdQA7AqAIAIQAkAfAIAjQAEAQADAjQAFAeARALQAMAIAbAAQAdAAALAGQAhg8gJhIQgLhHgwgwQgUgUgkgYQg0ghgIgGQgWgQhPhLQg8g5gwgWQABAJgLADgEhFoAXtQg+gqgsg0Qgwg6gWhAQgQgygFhCQgDgnAChQQABgsADgVQAFgkAMgbQAdg+BhgyQBGgkClg8QCbg4BOgsQCPhQBmiCQAXELgJENQgEBLgEAvQgIBDgRA1QgTA9gnBGQg9BuhSBEQhfBQhpAGIgUABQhtAAhxhNgEgsYgFQQgbgEgYgQQgkgaggg8QhMiMgMijQgMijA3iVQAbgkA4gNQAmgIBCABQAnABAUACQAhAEAZALQAPAHAXAPIAnAZQATAKAoASQAiARAPAVQASAXABAhQABAdgLAfQgIAVgRAiQgWAngGAQQgLAZgMAsQgPA1gGARQgUA6gnA+QgdAugyA/QgaAigUAKQgRAJgVAAIgPgBg");
	this.shape_1.setTransform(996.25,586.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.winner_mc, new cjs.Rectangle(0,0,1992.5,1172.3), null);


(lib.Window = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Background, null, new cjs.Matrix2D(0.398,0,0,0.359,-1243.2,-187.1)).s().p("AE2J4Qi1hOithQIAQmWQAIjEAKjCQAEhVAChYQgBgPgLAMQgSDDgKDIIgUGYQgDBCgBBVQj9hWkChyIjxhpQgHgdAAgnQAAgcAHgTIgCirQgBhEAHg6IgCjGQgBhMAHhDQgBguABhQIAAhkQEFBkEQBtQEKBrELBpIIXDQQAXAJAOAPIACCTQABA4gHAvQAACTACCmQABB4gHBuQgCAKAFADQABABAAAEQgGAyABA9IABBSQj7hVkBhwgAMTGhQiJB0iFB5IgBADQACAIAKgBQCKh1CJh4QADgMgKAAQgEAAgFACgAKjGEQhZA8hJBNIgBADQgHABgCAGIgDAEQAKANAOgNQAEgEACgHQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQBKhCBSg6IADgBQADgNgKAAIgJACgAmNj6IgBADIgMAIIgEADQgEAJgFAJIgDAEQgMAGgFAPIgDAEQgMAGgFAPQAAAAgBABQAAABAAAAQAAABgBAAQAAAAgBABIgQAOIgEAEQgBAMgJAFQgBAAAAAAQAAABAAAAQgBABAAABQAAAAAAABQgIAGgGAHQgCACAAADQgKADgDALIgDAEQgIABgBAKQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAABIgIAEIgEADQgEANgLAHQAAAAAAABQgBAAAAABQAAAAAAABQAAABAAABQACAEADABQADACAEAAIAIgDQgDgIAGgBIABgCQAFgEAFgFQACgCAAgEQAFgDAFgFQABgCAAgEQAIgFAHgHQABgCAAgEQAGgEAFgFQABgCAAgDQAIgGAGgHQACgCAAgDQALgDADgLIACgEIAQgPIAEgDQAAgKAIgCIAEgDIAJgRIADgEQAHgEAFgHIAEgDQgBgKAHgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAMgJAKgLQACgCAAgEIgFgFQgDgCgEAAIgPAPgArghDQAEgDAIgBIABgHIACgEIAIgEIAEgDQAEgNAMgGIAEgCQADgOANgFIAEgDQAFgPAPgHIAEgDQAFgPAPgHIAEgDQADgOANgFIAEgDQADgNAMgFIAFgDQADgOAMgFIAFgDQAFgPAOgHIAFgDQABgMAKgDIAEgDQAEgOAMgFIAEgCQAEgOAMgFIAEgDQADgOANgFIAEgCQADgOANgFIAEgDQADgOANgFIAEgDQAFgPAPgHIAEgDQAJgTARgMQACgBAAgEQAAgHgFgCQgDgBgEAAQgRAKgMAOIgDABQgFAPgPAHIgEADQgDAOgNAFIgEACQgDAOgMAFIgFADQgDAOgMAFIgFADQgBALgKAEIgFACQgDAOgMAFIgEADQgEAOgMAFIgEADQgCALgKAEIgEADQgEANgMAFIgEADQgDAOgNAFIgEADQgDANgNAFIgEADQgDAOgNAFIgEADQgDANgMAFIgFADQgDAOgMAFQgDABgCACQgFAPgNAJQgCABAAAEQgGADgEAFQgCACAAAEIgLAHIgEAEQAAAHgEADIgEAEQgDAKALgBgADmlGIgRARIgDABQgGANgLAIIgDABQgGANgLAHIgDABQgGANgLAIIgDABQgIAPgNAJIgDABQgFAPgOAIIgBACQADAKANgDQAKgNAOgIQAIgPANgJIADgBQAGgNAKgIIAEgBQAHgPANgJIAEgBQAOgSAPgRIACgBQADgNgJAAIgJACgAC+l8QgGAIgHAGIgDABQgEALgJAGIgDABQgEALgJAGIgDABQAAAHgFADIgDAAQgCAKgFAGIgBACQALARAFgUQAJgGAGgJIABgDQAKgHAFgLIABgEQASgMAOgQQACgKgIAAQgEAAgGACg");
	this.shape.setTransform(82.7801,82.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#689999").s().p("AioEMQgFgFgBgOQgBgPAFgGQADgEAFgDIAIgFQAJgGAMgWQAIgNANgQIAYgcQALgOApg6IAYggICEiyIAKgOQALgOAGgDQAOgHAIAIQAIAGgDANQgCAHgJAMIkmGMQgJANgHADQgFADgFAAQgGAAgFgEgAiggvQgEgGAAgIQABgHAEgHQACgFAQgRQAHgIAUgeIASgaIATgYQAZgfAJgPQANgWAEgFQAMgOAPABQAIABAGAGQAGAHgCAIQgBAFgKALQgIAJgKAOIgrA6IgBACQgYAggLARIgLARIgMAMIgGAMQgEAHgDAEQgGAHgIACIgDAAIgCAAQgKAAgGgHg");
	this.shape_1.setTransform(40.0595,73.3689);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002517").s().p("AgnEcQgTgEgNgPQgOgPgBgTQgCgcAfgoQATgXAQgQIAWgZIAXgWIAegXQAegYAUgeIASgeQAMgRANgIQAOgIARAAQARgBAOAJQAOAIAIAPQAGALABALIiFCyIgNALIgdAeQgOAQgEAGIgQAaQgMAQgRAHQgMAFgMAAIgOgBgAjfDMQgIgKgEgOQgDgNADgNQAFgVAXgWQAdgWANgMQAbgWAig0QAmg4AUgUIAVgVQANgNAIgKIAOgXQAJgPAHgHQAHgJATgOQASgOAHgIQAGgHATgdQAOgWANgJQAOgJARgBQASAAAOAIQAPAIAIAPQAIAQgBAQQgCATgUAgQgVAjgQAQIgUATIgUATQgJAJgOATIgXAdIgOAOIAsg6QAKgPAIgIQAKgMABgFQACgHgGgHQgGgGgIgBQgPgCgNAPQgEAEgNAXQgIAOgZAgIgUAYIgRAYQgTAfgHAIQgQARgDAFQgEAHAAAHQgBAIAFAFQAGAJALgBIADgBQghAxg9AxQgiAagaABIgDAAQgbAAgRgVg");
	this.shape_2.setTransform(28.3125,59.2431);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.bf(img.Background, null, new cjs.Matrix2D(0.398,0,0,0.359,-1201.6,-169.4)).s().p("AFzKLIARmWIADhJIgRHgIgDgBgAijGxIjwhpQgIgdABgnQAAgcAHgTIgCisQgBhDAGg6IgBjGQgBhMAGhDQgBguABhQIAAhkQEFBkEPBtIEUBuIgBAOQAAgPgMAMQgSDDgJDHIgUGZQgEBCAABVQj9hWkChygAgvCNQgoA5gMAOIgXAcQgOARgIANQgMAVgIAGIgJAGQgFADgCADQgFAHABAPQABANAFAFQAIAIANgHQAGgDAKgNIEmmMQAIgMACgGQADgNgHgHQgJgIgOAHQgGAEgKANIgLAPQgBgMgGgLQgIgPgOgIQgOgJgRABQgRAAgOAIQgNAIgLARIgSAeQgUAfgeAYIgeAWIgXAWIgXAZQgQAQgTAXQgfAoACAcQABATAOAPQANAPATAEQATAEATgIQASgHAMgQIAQgaQAEgGAOgQIAdgeIANgKgAAglYQgRABgOAJQgMAJgOAWQgTAdgGAHQgHAIgSAOQgTAOgHAJQgHAHgJAPIgPAXQgIAKgNANIgVAVQgUAUgmA5QgiA0gbAVQgNAMgdAWQgXAWgFAVQgDANADANQAEAOAIAKQASAWAdgBQAagBAigaQA9gwAhgyQAIgBAGgHQAEgEADgIIAHgLIALgMIAMgQQAKgSAYggIABgBIAOgOIAXgdQAOgTAJgJIATgTIAUgTQAQgQAVgjQAUggACgTQABgQgIgQQgIgPgPgIQgNgIgRAAIgCAAg");
	this.shape_3.setTransform(41.1484,65.2125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.bf(img.Background, null, new cjs.Matrix2D(0.352,0,0,0.359,-1135.1,-203)).s().p("AhIHZQifhOiZhQIAarrIACgyQADhRAChUIAAgHIAAgPIDlBmIAaALIBIAgIF2ClQAVAKANAOIABCTQABA5gGAvIACE4QABB4gGBuQgDAKAFADQABABAAAEQgGAzACA8IABBTQjfhWjihvgAEZEMQgMAIgSAVIg1BAQgIALgHAGIgRALQgHAEgYAYQgTATgOAKIgQAPQgJAIgEAIQgGAOAAAMQAAANAGAIQAGAIAOAEQAOADALgDQANgEAUgXIAegjQAOgRAKgJIASgPQAbgXAYgcQAagcAIgHQgDAPAGAJQACAGAGACQAEADAGgBQAHgCAHgPQATgkALgmQAHgUgCgNQgBgJgFgHQgFgGgHgCQAAgMgKgFQgLgFgHAJQgEAEgEAKIgHAXIgDgBQgQAAgRAMgADzC9QgDADgGANIgQAcIgIAOIgOANQgKAKgLAOIgPATQgNARgIAHQgOANgVAGQgWAGgEAKQgBAEAAAJQAAAIADAFQABAEAHADQAPAFAMgIIAQgOIAVgPQAOgKAHgHQAEgDAOgVQAIgMALgLIAFACQAKAAAMgJQAKgHAPgRIAXgaQAIgHADgFQADgFgBgHQgBgHgEgFQgDgFgGgBQgGgBgFACIgBABIgDgIQgEgHgIgCIgDAAQgGAAgFAEgABzi9QgIADgLAMIgaAhIhuCUQhaB5grBEIggAzQgSAdgQASQgRAVgCANQgDAKAGAJQAFALAIgBQALgBALgUQAKgSAQgZQCDjLCWjAQAUgcAOgOQAKgIAEgIQAHgMgGgKQgCgGgHgBIgGgBIgGABgAB+BbQgDAEgDAJIgFAMQgEAIgJAKIg/BMQgIAKgBAFQgDAKAHAIQAGAKAJgCQALgCAMgTQAMgTATgWIASgUIARgVQAMgRAJgSQAFgJAAgJQgBgHgFgEQgEgGgHAAIgCAAQgMAAgHANgAhFkUQgMABgRASQguAwglA/QgHALAAAHQABAHAGAEQAFAFAHgBQAKgBAKgNIANgWQAGgLARgXQASgYALgJQAIgIASgOQAKgJABgIQABgJgHgHQgHgFgHAAIgCAAgAj/k1IgBAEIAAAAIgFALQgFANAIAJQAEAFAHABQAFAAAFgCQAGAAAFgEQAEgEACgJIADgGIAohAIAaguQAOgaAHgYIABgBQAKgOABgMQABgHgDgGQgDgIgGgBQgIgDgJAIQgFAFgIAMIgYAeQgMAOgMASIgCAEQgEgGgIgCQgLgDgHAGQgGAGgBAMIABAUIABARIgIAHIgQANQgJALAEALQABAFAFAEQAGACAFAAIABAAgAi6oZIgJAGIgIAHIgIAGIgHAFIgGANQgDAGgLAGQgbAUgJAKQgPAQAFAOQADAGAIACQAGACAHgDQAFgCAGgFIALgJQAIgHATgOIAigiQAFgGAGgDIALgHQAJgKgDgLQgEgIgKgEIgIgBQgIAAgHAFgABoHtIAGgEIAEgCIADAAIgHAHIgBADIgGABQAAAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAgBg");
	this.shape_4.setTransform(39.5577,66.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#689999").s().p("AjPE0QgGgKADgKQACgNARgUQAQgTASgdIAggzQArhEBZh4IBviVIAaghQALgMAIgDQAGgCAGACQAHACACAFQAGAKgHAMQgEAIgKAJQgOAOgUAbQiWDAiDDMQgQAYgKASQgLAUgLABIAAAAQgIAAgFgJgABSDMQgHgJADgKQABgFAIgKIA/hLQAJgLAEgIIAFgMQADgJADgEQAHgOAOABQAHABAEAFQAFAFABAHQAAAIgFAJQgJASgMARIgRAVIgSAVQgTAVgMAUQgMATgLABIgCAAQgIAAgFgHgAiFicQgGgFgBgGQAAgIAHgLQAlg/AugwQARgRAMgCQAIgBAIAHQAGAHgBAJQAAAHgKAJQgSAOgIAIQgLAKgSAXQgRAXgGALIgNAXQgKANgKAAIgCAAQgGAAgEgDg");
	this.shape_5.setTransform(34.7632,70.9445);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002517").s().p("AAvIaQgOgDgGgJQgGgHAAgNQAAgMAGgOQAEgJAJgIIAQgOQAOgLATgSQAYgYAHgEIARgLQAHgGAIgLIA1hAQASgVAMgIQASgNASABIAHgWQAEgLAEgEQAHgIALAFQAKAFAAAMQAHABAFAHQAFAHABAJQACANgHATQgLAngTAkQgHAOgHACQgGACgEgDQgGgDgCgFQgGgJADgPQgIAGgaAdQgYAcgbAXIgSAPQgKAJgOARIgeAjQgUAXgNAEIgLABQgHAAgHgCgABEHqIgEACIgGAEQAAABgBABQAAAAAAABQAAAAAAABQAAAAAAABIAGgBIADgCIAJgIIgEAAIgCAAIgBAAgAAqGOQgHgDgBgEQgDgFAAgJQAAgIABgEQAEgLAWgFQAVgHAOgNQAIgGANgRIAPgTQALgOAKgKIAOgNIAIgOIAQgcQAGgNADgDQAGgGAIACQAIABAEAHIADAJIABgBQAFgDAGACQAGABADAFQAEAFABAGQABAHgDAFQgDAGgIAHIgXAaQgPAQgKAIQgMAJgKgBIgFgBQgLALgIAMQgOAUgEAEQgHAHgOAJIgVAQIgQAOQgIAFgIAAQgFAAgGgCgAklkHQgHgBgEgFQgIgJAFgOIAFgKIAAAAIABgEIgBAAQgFAAgGgDQgFgDgBgGQgEgLAJgKIAQgOIAIgHIgBgQIgBgVQABgLAGgGQAHgGALACQAIADAEAGIACgEQAMgSAMgOIAYgeQAIgMAFgFQAJgIAIACQAGACADAHQADAHgBAHQgBALgKAOIgBACQgHAXgOAaIgaAuIgoBBIgDAGQgCAJgEAEQgFAEgGAAQgEACgEAAIgCAAgAk/mhQgIgCgDgHQgFgNAPgQQAJgLAbgTQALgHADgFIAGgNIAHgGIAIgFIAIgHIAJgGQALgIAMAEQAKAEAEAIQADALgJAJIgLAHQgGAEgFAFIgiAjQgTANgIAIIgLAJQgGAFgFACQgEACgEAAIgFgBg");
	this.shape_6.setTransform(44.1984,66.6747);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#689999").s().p("AE2J4Qi1hOithQIAQmWQAIjEAKjCQAEhVAChYQgBgPgLAMQgSDDgKDIIgUGYQgDBCgBBVQj9hWkChyIjxhpQgHgdAAgnQAAgcAHgTIgCirQgBhEAHg6IgCjGQgBhMAHhDQgBguABhQIAAhkQEFBkEQBtQEKBrELBpIIXDQQAXAJAOAPIACCTQABA4gHAvQAACTACCmQABB4gHBuQgCAKAFADQABABAAAEQgGAyABA9IABBSQj7hVkBhwgAIFKOIgBADIAEgCIAJgIIgEgBIgIAIg");
	this.shape_7.setTransform(82.7801,82.925);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]},1).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_7}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,165.6,165.9);


(lib.Volleyball = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-648.1,-568.8)).s().p("ABGCuQiqAahNhkQgFgFgDgGQg4hWALiGQB1hEC6AdQAFAKAHADQA+AWAuAZQAFAKAGAJIATAWIAKCfQgKAPgOAJQgTAMADAiIgoAAIgUAUQgtgKgSAEg");
	this.shape.setTransform(23.277,17.9415);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.People, null, new cjs.Matrix2D(0.665,0,0,0.6,-1083.2,-950.7)).s().p("AB1EiQkdAsiAinQgJgJgGgKQhdiPATjgQDDhyE3AwQAJARAMAFQBoAlBMAqQAIAQALAPQAOATARARIARELQgRAZgXAPQggAUAFA5IhDAAIghAhQhMgQgdAGg");
	this.shape_1.setTransform(23.3067,17.9262);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-648.2,-568.8)).s().p("ABxEgQgBgDgEgDQgFgFgJgCQgPgDgNAAQgOAAgEgCIgKgMQgJgKgVgGQgZgIgzgBIgEAAIgBAAIgFAAQgQAAgIADQgJADgDAGQgKgDgOgBIgXgBQgMgCgJgFQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAQghgcgagoQgHgJgFgKQhMiPAQjgQCfhyD/AwQAHARALAFQBVAlA+AqQAHAQAJAPQALATAOARIAOELQgOAZgTAPQgaAUAEA5Ig3AAIgbAhQgsgLgZgBg");
	this.shape_2.setTransform(23.3116,17.9262);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AkakaIEpAAIEMAAIAAI1IjEAAIgcAAIhMAAIh0AAIiVAAIAAhgg");
	this.shape_3.setTransform(31.6,19.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.bf(img.People, null, new cjs.Matrix2D(1,0,0,1,-2100,-1500)).s().p("ABXEaIgcAAIhLAAIh0AAIiWAAIAAhfIAAnVIEpAAIELAAIAAI0g");
	this.shape_4.setTransform(31.6,19.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-642.2,-568.8)).s().p("ADKEmIAcAAIgFAGIgXgGgAAJEmIB0AAQggAFgdAAQgdAAgagFgAigCnQgHgJgEgKQhGiPAPjgQCQhyDoAwQAEAKAEAFIkpAAIAAHVQgLgPgKgRg");
	this.shape_5.setTransform(17.3499,17.9262);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.6,-12.1,77.8,60.5);


(lib.Swim34 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Swimmer2();
	this.instance.setTransform(0,0,0.3807,0.3807);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Swim34, new cjs.Rectangle(0,0,236.4,150.4), null);


(lib.Swim3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-119.4,-805.5)).s().p("AAVPXQgngFgoAAIgbhOQhSjrhrkOQgEgIAAgKQhDgShBgLIgKgCQhEgKhGABQhOgtiPghQgKgCgKAAIgUg8QgmgDgCgUQgIg7hIAWIgohRIg8g7QgKAAgBgDQgPgzg2gGQgyhyAHiSQADg7AAg9QBMihg4kEIC0h4IEFAAQAcAQAkApQAHAHAJAGIABAAIACABQAPAIAWABQAwARASAXQARAWAlASQAbAbAjAaQAsAfA4AdIA6AcQAlASArABIAUA8IBQAVQAzBaBJBIQAsAqA0AkICMAUQDfA1EWAbQAOAwA2AWQASAHA4ADIASAAIAUAoIBkAUQAWAoAYA6QAOAfAUAeIg8EFQhGBQhfBfQgFAFgKAAIkYgUQgFgLgHgJIAMA8QAUAKAIARQAMAXAAAeQAJB+iWgEQg7gCg9AAIhkA9IgUB4QhQBXiSAAQgaAAgdgCg");
	this.shape.setTransform(116.3566,98.5403);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Swim3, new cjs.Rectangle(0,0,232.7,197.1), null);


(lib.Swim2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Swimer3();
	this.instance.setTransform(0,0,0.4106,0.4106);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Swim2, new cjs.Rectangle(0,0,250.1,201.7), null);


(lib.Swim1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-119.4,-805.5)).s().p("AAVPXQgngFgoAAIgbhOQhSjrhrkOQgEgIAAgKQhDgShBgLIgKgCQhEgKhGABQhOgtiPghQgKgCgKAAIgUg8QgmgDgCgUQgIg7hIAWIgohRIg8g7QgKAAgBgDQgPgzg2gGQgyhyAHiSQADg7AAg9QBMihg4kEIC0h4IEFAAQAcAQAkApQAHAHAJAGIABAAIACABQAPAIAWABQAwARASAXQARAWAlASQAbAbAjAaQAsAfA4AdIA6AcQAlASArABIAUA8IBQAVQAzBaBJBIQAsAqA0AkICMAUQDfA1EWAbQAOAwA2AWQASAHA4ADIASAAIAUAoIBkAUQAWAoAYA6QAOAfAUAeIg8EFQhGBQhfBfQgFAFgKAAIkYgUQgFgLgHgJIAMA8QAUAKAIARQAMAXAAAeQAJB+iWgEQg7gCg9AAIhkA9IgUB4QhQBXiSAAQgaAAgdgCg");
	this.shape.setTransform(116.3566,98.5403);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Swim1, new cjs.Rectangle(0,0,232.7,197.1), null);


(lib.Score = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Scorepannel();
	this.instance.setTransform(0,0,0.3897,0.3897);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,126.3,110.7);


(lib.Scaryghost_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Scaryghost();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,138,151);


(lib.rotate_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Rotationgirl();
	this.instance.setTransform(0,0,0.3351,0.3351);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DB0000").s().p("AkjIUIgCgBIAAgCIAGgDIABgDIABgCIABgCQAFgBAFgBIABAAQAIgEAFgEIAAgDIACgCQAEgGAGgEIABgCIADgBIABgBQAHgFAEgGIACgBIABgCIABgCIAJgIQAAAAAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIABgCIABgCQADgFAFgBQABgJACgGIAOgkIgBgCIgBgBIgBgHIAAgCIAAgDIADgBIgBgDIgCgBIAAgCQAEhNAPhDIALgpIACgBIACgBIACgBIAAgEIABgCQAFgBgCgHIACgBIACgCIADAAIAAgDIAAgDQAHgCgBgJIAGgBIABgCQABgGAGgBIAAgCIABgBQABgJAIgCIAAgDIAAgCQAHgFAEgJIACgBIABgCIACgBQAEgFACgFIABgDIADgBIABgCIAGgEIAAgDIABgDIAGgEIAIgUIAPghIAAgDIgCgCIgBgCIADgBIAAgDQAAgIACgIIACAAIgBgDIgBAAQgCgIACgIIACgBQgHg9gJg7IgIgvQAAghAKgoQAFgTAJgTQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAIgBgCQgDgFgFgFIAAgCIgDgBIgCgCIgFgEIAAgEIgBgCQgEgEgCgHIAAgDIgDgBIgBgCIgDgBQgEgUgFgRIgLgrIAAgDIAAgCQAGgBgDgHQgBgDABgEQAFgQAJgOIACgBIACgBQAFgCABgGQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAABAAIADgDQAGgJAKgDIABgDIACgBIAEgGQADAAADgCIABgBIADgDQAcgMAjgCIgEAAIADgEIApAAIABACQAAAAABABQAAAAABAAQAAABABAAQAAAAABAAIABAAIABADIACABQAHADAEAHIACAAIACACIACAEIADABIABABQAFABgCAHIAGACIABABQABAGAGABIAAADIAAADIAGAEIAAADIABADIAGAEIAAADIAAADQAFAAgCAIIADABIABABIADABQAIAbACAeQACAZgJASIABADIACACIAEACIAAADIABADIAGAEQAAAEABACQAJAPgGAQIgBADIABADIABABQABAGAAAHIADABIACACQAEAEACAHIACABIACABQAEAEACAHIACABIACABQAFACgDAKIADAAIABACIADAAIAAAEIABADIAHAKIACAAIABADIABABQACALAJADIAAACIADABIACACQAEAEAFADQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABAAIABABQABAJAHABIAAADIABADQAEAEABAHIABADIACABIACABIACABIAAAEIABACIAGAIIAAABIAJAFQADAAABAEIADABIACABQAEAFADAFIACACIAAADIAAADIAAAEIACAAIACACIACABIAAADIABAEIADANIAAAAIgBADIgBABQgDAGgEAEIgBACQgIAGgJACQgUACgNgGIgBgDIgBgBQgDgFgGAFIAAADIgCACIgVAMIABADIABABQACAGAGAAIAAAEIAAADQgCAKgGAGIgCABIgBADIgCABQgNAHgOAFIgDgBIgBgBQgJgBgEgHQgDAAgDACIgBABQgGAEgHADQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgCABIgKAHQgQAigGAuQgDAXgMAOIgBACIgBACQgGAKgHAIIgCABIgBADIgCACIgIAIIgCABIgBACIgCACIgIAIIgDABIAAAEIgBACQgEAFgFADIAAADIAAABQgFACACAHQgEAAgCABIgBADQgBAFgGABIAAAEIAAACQgEAHgFAEIgBADIgCABIgBACIgGAEIAAADIgBADIgFAEIAAAEIgBACIgGAEIAAADIgBADIgIAPIgBACIgDABIgBACQgKAJgBATIgCAAIAAACIgJACQgEACAAAHIgDABIgCABIgIAJQAAAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABIgCABIgCABQgHAFgEAIIgBABIgBADIgCACIgJALIgCABIgBADIgBABQgBAIgHACIAAACIAAAEIAAAEIgCAAIgCACQgEAEgCAHIgDAAIgBACQgHAFgEAJIgCAAIgBADIgBACIgJAIIgCABIgBACIgBACQgEAGgHAEIgBADIgCABIgCABQgFACgBAGIgGABIgBACIgDADQgDAAgDACIgBACIgDADQgDAAgDABIgBABQgJADgHAFQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIgCACQgGAEgLABIgBADIgCACIgBACIgKAAIAAAEIAAACQgLAEgFAKIgDABIgBABQgKAAgHgCgAi/G2QgDAFABAIQgGAFgEAGIAAADQgHAJgKAEQAEANAGgNQAMgBAFgJIAUgNQAEgJAIgGIABgCQAHgCAEgHIADgBQAEgJAGgHIADAAQADgHAFgGIACgBIAGgOIABgCQAHgBAAgKIgBgDQANgFAEgMQAGgBACgFIACAAQAAgHADgEIABgDQALgGAFgLQAIgDAEgGIACgBQAAgHAEgCIACgBQAEgNAGgLIAAgDIAEgCIADgBQACgKAGgGIACgBIAGgKIABgDQAGgEADgHIAAgCQAGgCAAgGIABgCIADgEIADAAQAAgHAEgCIADgBQACgLAHgHIABgCQAKgFAFgMIACAAQABgGAFgCIABgCQAJgCAEgIQAFgEADgFIACgBQAAgGAEgDIADgBIAQhNQAIgjAJgjQgegEgUgQQgDgHgGgEIgBgCQgMgDgFgLQgHgDgEgJIgCgBIgIgNIgCAAQgSgngRgpQgSgqgDgqQgIgLAOAHQAIAoANAiIAdBKIADACIADABQAAAJAEAEIADABQAEALAJAHIABACQAIAEAGAIIACABQADAHAHAEIAAADQAaAWA3gGQAAAIAGACQgCAFAHALQAAAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAQATAHALgOQAGAAgBgHIACAAQgCgGgEgFIgBgCQgJgCgEgIQgLgCgJgEQgGgMgLgGQgDgMgKgGIAAgBQgJgHgIgHQgHgIgGgJIgBgDQgJgFgFgLIgCgBQgDgHgHgEIAAgCQgNgRAQAKIAGAEIABADQAFABABAFIAAAEQAMAJAJALIAKAMIADACIALAMIACABQAIAQAFgQIABgDQAFgCADgFIACAAQAKgYgIgkQgCgIADgMIAEAAIAJANIABADQALAGAFALIANALIABACQAHAEAEAJIACABQAKAUAFAYQADAIADAHIADABQAOAMATgMQADgDACgHIACAAQgFgOgHgNIgCAAQgBgHgEgEIgBgCIgbgHQABgGAFgCIABgCQgJgOgGgQQAAgBAAAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQgGAAgBgHIAAgDQgJgFgIgIIgMgRIgBgDQgJgIgEgNIAAgCQgHgFgDgGIAAgDQgIgEgEgJIgCAAIgIgNIgCgBQAAgHgEgCIgDgBQAAgHgEgCIgCgBQAAgHgEgCIgDgBIgFgRIgCAAQgCAJgHAGIgBACQgFAFgIACIgDADIgBADQhHAXhBgQQgLAdgFAjQgDAdAGAVIgDADIgBAEQALA2AGA5QAHA7gKAvIgEACIgDABQABALgEAGIAAADIgEADIgDABQAAAGgDAEIAAADIgEADIgDAAQgBANgIAFIgBACQgJAFgEAJIgBADQgIAFgEAIIgBAEQgIAEgDAIIgCABIgGAKIgBAEIgEACIgDABQAAAHgEACIgCABQgOAagIAiIgMA8QACAQgDAcIgCAEIADAGIAAAEQgEAIADAFIABAEQgFADADAJIgBAAQADAWgLAWgAB/geIgDANIAAAEIAUgKQACgKgIAAQgEAAgHADgACmhoIgCABQgLAMAEALIAAADIAKAIIABADQAJAAAEAGQAUgFAKgPQAKgBAAgJQAAgXgLgNIgCgBQgDgJgHgGIAAgCIgKgIIAAgCQgEgFgGgCQACAkgOAVgAgkkxIAAAEIgCABQgBAAAAAAQAAAAAAAAQAAABAAAAQAAAAABAAIAFAFIAEADQBGAFA4gdIADgBIABAAQAFgBABgIQAAgCAEgBIAAgDIACgBIACgFQACgDAEgCIgBgCIgCgBIgCgCIgBgCIgBgDIACgBIACAAIAJgDIAAgDQAKgLgCgZQgBgbgHgUIgCgBIgCgBIgCgBIAAgEIgBgCQgFAAgCgGQgBgBACgIIgDgBIgBgBIgDgBQACgHgEgCQgEgBgDgGQgBgDgDgBIgBgCIgCgCIgFgFIgGgFIAAgCIgCgBIgCgCIgCgBIgEgEQgEgHgJgBQgPgBgPgBQggAEgZAMIgGACIgBACIgBABIgBADQgEAAgCACIgCAAIgFACIgBACIgDAEIgHAGIgGAEIAAADIgBAEIgDADIgGADQgSAVAFAeIAJAyIADABIABACIADABQAAAEACAEQAEAFAEAIIADAMQAEABABADIAFAJIAEAHQADAAADgBIAAgCIABgDIACgCIABgCIACgBIACgBQAEgBAFABIAAACIAAADIAAACIgEAAQgIAAACAIgACFk6IABADIAEADIADAAQABAJAFAFIAAADQAIgPgJgNQgCgEAAgFQgIgEgDgJIgCgBIgGALIgBADQgKAEARgBQAAAHACAEg");
	this.shape.setTransform(29.8375,53.35);

	this.shape_1 = new cjs.Shape();
	var sprImg_shape_1 = cjs.SpriteSheetUtils.extractFrame(ss["Assignment_4_atlas_1"],4);
	sprImg_shape_1.onload = function(){
		this.shape_1.graphics.bf(sprImg_shape_1, null, new cjs.Matrix2D(0.335,0,0,0.335,-29.6,-53.4)).s().p("AkoIXIAAwtIFBAAIgDAEIAEAAQgjACgcAMIgDADIgCABQgCACgDAAIgFAGIgBABIgBADQgKADgGAJIgDADQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQgCAGgEACIgCABIgDABQgIAOgFAQQgCAEACADQADAHgGABIAAACIAAADIALArQAFARAEAUIACABIACACIADABIAAADQABAHAEAEIABACIAAAEIAGAEIACACIACABIABACQAEAFADAFIABACQABAAAAAAQAAABAAAAQAAAAAAABQABAAAAAAQgKATgFATQgKAoABAhIAIAvQAJA7AHA9IgDABQgBAIABAIIABABIACACIgDAAQgBAIAAAIIgBADIgCABIABACIABACIABADIgQAhIgHAUIgGAEIgBADIAAADIgGAEIgCACIgCABIgBADQgDAFgDAFIgCABIgBACIgCABQgEAJgHAFIgBACIAAADQgHACgBAJIgBABIAAACQgGABgBAGIgBACIgGABQABAJgHACIAAADIAAADIgDAAIgCACIgDABQACAHgEABIgBACIAAAEIgDABIgBABIgCABIgLApQgPBDgEBNIAAACIACABIABADIgDABIAAADIAAACIABAHIABABIABACIgPAkQgBAGgBAJQgGABgCAFIgBACIgBACQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIgJAIIgBACIgCACIgCABQgEAGgGAFIgBABIgDABIgBACQgGAEgFAGIgBACIgBADQgFAEgHAEIgBAAQgFABgFABIgBACIgCACIgBADIgGADIAAACIADABQAHACAKAAIABgBIADgBQAFgKALgEIAAgCIAAgEIAKAAIABgCIABgCIABgDQALgBAHgEIABgCQABgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAgBQAGgFAKgDIABgBQACgBAEAAIACgDIACgCQADgCADAAIADgDIABgCIAGgBQABgGAFgCIABgBIADgBIABgDQAGgEAFgGIABgCIAAgCIADgBIAIgIIACgCIABgDIACAAQADgJAIgFIABgCIACAAQACgHAFgEIABgCIADAAIAAgEIAAgEIAAgCQAHgCABgIIABgBIABgDIACgBIAJgLIABgCIABgDIACgBQAEgIAHgFIACgBIACgBQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAIgJIACgBIACgBQABgHAEgCIAJgCIAAgCIABAAQACgTAJgJIACgCIADgBIABgCIAIgPIABgDIAAgDIAGgEIABgCIAAgEIAFgEIABgDIAAgDIAFgEIABgCIADgBIABgDQAFgEAEgHIAAgCIAAgEQAGgBAAgFIABgDQADgBADAAQgBgHAEgCIABgBIAAgDQAFgDAEgFIABgCIAAgEIADgBIAIgIIABgCIABgCIADgBIAIgIIACgCIABgDIACgBQAHgIAFgKIABgCIABgCQAMgOAEgXQAGguAQgiIAKgHIACgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAAAQAGgCAGgFIACgBQADgCADAAQAEAHAJABIABABIACABQAPgFANgHIACgBIABgDIACgBQAGgGACgKIAAgDIAAgEQgGAAgCgGIgBgBIgBgDIAVgMIACgCIAAgDQAGgFACAFIABABIABADQAOAGAUgCQAJgCAIgGIABgCQADgEAEgGIABgBIABgDIAAJogAjaHdQAKgEAGgJIABgDQADgGAHgFQgCgIAEgFQALgWgDgWIABAAQgEgJAGgDIgBgEQgDgFAEgIIgBgEIgCgGIACgEQADgcgCgQIAMg8QAHgiAPgaIACgBQAEgCAAgHIADgBIADgCIABgEIAHgKIABgBQAEgIAIgEIABgEQAEgIAIgFIABgDQAEgJAIgFIACgCQAIgFABgNIADAAIADgDIABgDQADgEAAgGIACgBIAEgDIABgDQAEgGgBgLIADgBIAEgCQAJgvgGg7QgGg5gLg2IAAgEIADgDQgGgVAEgdQAFgjALgdQBBAQBHgXIABgDIADgDQAIgCAFgFIABgCQAGgGADgJIACAAIAFARIACABQAFACAAAHIACABQAEACAAAHIADABQADACABAHIACABIAIANIACAAQADAJAJAEIAAADQADAGAHAFIAAACQAEANAIAIIABADIANARQAIAIAJAFIAAADQABAHAFAAQABABAAAAQABABAAAAQAAABABAAQAAAAAAABQAGAQAIAOIgBACQgEACgBAGIAbAHIABACQAEAEABAHIACAAQAGANAGAOIgCAAQgCAHgDADQgTAMgPgMIgCgBQgEgHgCgIQgGgYgJgUIgCgBQgEgJgIgEIgBgCIgMgLQgFgLgLgGIgBgDIgJgNIgFAAQgDAMACAIQAJAkgLAYIgBAAQgDAFgFACIgBADQgGAQgHgQIgDgBIgKgMIgDgCIgLgMQgIgLgMgJIAAgEQgBgFgGgBIgBgDIgFgEQgRgKANARIABACQAGAEADAHIADABQAEALAKAFIABADQAFAJAIAIQAHAHAKAHIAAABQAKAGADAMQAKAGAGAMQAJAEALACQAFAIAJACIABACQAEAFACAGIgCAAQABAHgGAAQgMAOgSgHQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgHgLACgFQgGgCAAgIQg3AGgagWIAAgDQgHgEgDgHIgCgBQgGgIgIgEIgBgCQgKgHgDgLIgDgBQgFgEABgJIgDgBIgDgCIgdhKQgOgigHgoQgPgHAJALQADAqARAqQARApATAnIACAAIAHANIACABQAFAJAHADQAFALALADIACACQAGAEADAHQAUAQAeAEQgKAjgHAjIgRBNIgDABQgDADAAAGIgCABQgDAFgFAEQgFAIgJACIgBACQgEACgCAGIgCAAQgEAMgKAFIgBACQgHAHgCALIgDABQgEACAAAHIgDAAIgDAEIgBACQAAAGgHACIAAACQgDAHgGAEIAAADIgGAKIgDABQgFAGgCAKIgDABIgEACIgBADQgFALgEANIgDABQgDACAAAHIgDABQgEAGgHADQgGALgLAGIgBADQgCAEAAAHIgCAAQgCAFgGABQgEAMgNAFIABADQAAAKgIABIAAACIgHAOIgCABQgEAGgEAHIgCAAQgGAHgEAJIgDABQgEAHgHACIgBACQgIAGgEAJIgUANQgGAJgLABQgEAHgCAAQgCAAgCgHgAB+gSIADgNQATgHgCAOIgUAKIAAgEgACqhDIgBgDIgKgIIAAgDQgFgLAMgMIACgBQAOgVgCgkQAGACADAFIABACIAJAIIABACQAHAGACAJIADABQALANAAAXQAAAJgKABQgKAPgVAFQgDgGgJAAgAEmheIgBgEIAAgDIgDgBIgBgCIgCAAIAAgEIAAgDIAAgDIgCgCQgEgFgDgFIgCgBIgDgBQgBgEgDAAIgJgFIAAgBIgGgIIgBgCIAAgEIgCgBIgCgBIgDgBIAAgDQgBgHgEgEIgBgDIAAgDQgIgBAAgJIgBgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQgBAAAAgBQgEgDgFgEIgCgCIgCgBIAAgCQgJgDgCgLIgBgBIgBgDIgCAAIgIgKIgBgDIAAgEIgCAAIgBgCIgDAAQADgKgGgCIgBgBIgCgBQgCgHgFgEIgBgBIgCgBQgDgHgEgEIgBgCIgDgBQAAgHgCgGIgBgBIAAgDIAAgDQAHgQgJgPQgCgCABgEIgHgEIAAgDIAAgDIgEgCIgCgCIgBgDQAJgSgCgZQgCgegIgbIgDgBIgBgBIgDgBQACgIgFAAIAAgDIAAgDIgGgEIgBgDIAAgDIgGgEIgBgDIAAgDQgGgBAAgGIgBgBIgGgCQACgHgFgBIgCgBIgCgBIgCgEIgCgCIgDAAQgDgHgHgDIgCgBIgBgDIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgCgCIDoAAIAAHFIgDgNgAgbkkIgEgDIgFgFQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAIACgBIAAgEQgDgKANACIAAgCIAAgDIgBgCQgEgBgFABIgBABIgCABIgBACIgCACIgBADIgBACQgCABgDAAIgFgHIgEgJQgCgDgDgBIgDgMQgEgIgEgFQgCgEAAgEIgDgBIgCgCIgCgBIgJgyQgFgeARgVIAHgDIACgDIABgEIAAgDIAGgEIAIgGIADgEIABgCIAFgCIABAAQADgCAEAAIABgDIABgBIABgCIAGgCQAZgMAfgEQAPABAPABQAKABAEAHIAEAEIACABIACACIABABIABACIAGAFIAFAFIABACIACACQADABABADQACAGAFABQAEACgCAHIACABIACABIADABQgCAIABABQACAGAFAAIABACIAAAEIACABIABABIADABQAHAUABAbQABAZgJALIgBADIgJADIgBAAIgCABIABADIABACIACACIABABIACACQgEACgCADIgCAFIgCABIgBADQgDABAAACQgBAIgGABIgBAAIgCABQgwAZg7AAIgTgBgACUknQgEgFgBgJIgEAAIgDgDIgBgDQgCgEAAgHQgRABAKgEIAAgDIAHgLIACABQADAJAIAEQAAAFACAEQAJANgIAPIgBgDg")
	}.bind(this);
	this.shape_1.setTransform(29.65,53.45);

	this.shape_2 = new cjs.Shape();
	var sprImg_shape_2 = cjs.SpriteSheetUtils.extractFrame(ss["Assignment_4_atlas_1"],4);
	sprImg_shape_2.onload = function(){
		this.shape_2.graphics.bf(sprImg_shape_2, null, new cjs.Matrix2D(0.377,0,0,0.37,-33.4,-58.9)).s().p("AlNJOIAAyaIKbAAIAASag")
	}.bind(this);
	this.shape_2.setTransform(27.15,53.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#DB0000").ss(1,1,1).p("AnvslIPfAAIAAZLIvfAAg");
	this.shape_3.setTransform(31.575,52.625);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AnvMmIAA5LIPfAAIAAZLg");
	this.shape_4.setTransform(31.575,52.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19,-29,101.2,163.3);


(lib.ghost22_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1459.5,-52.5)).s().p("AhGH5QAAgegPgPQgZgZgogKIgog8QgcAAgXgLIBbBbQhpgpgrg0QgWgbgegUQgZhOhKg/IgpgnIgUkXIgog8QAAicALiaIQPAAQBNEcgnFEQgOB3AGB6QgoBwhyA8QgQAIgKAUg");
	this.shape.setTransform(55.0906,52.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost22_mc, new cjs.Rectangle(0,0,110.2,105.1), null);


(lib.ghost21_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-760.2,-149)).s().p("ApCHfQgrgghOgvIAUl8ICMiLIAAiMQAxgUAKg9QABgJAAgKIBQhQQBRgFgBg3IAAgUIE/AAQAKAAAAACQADAXANARIAeAIIAFAAQD9AdDiA9IAUA8IBkAUQAAAUAKAKQAKAKAUAAIAAErIg8A8IjIAoQgUAAgKAKQgKAKAAAUIksAoIgUA8Qg2AGgUAwQgGAQgTAKQgeAAgRAPQhVBLhYAyIkYAUIg7gpg");
	this.shape.setTransform(70,52);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost21_mc, new cjs.Rectangle(0,0,140,104), null);


(lib.ghost19_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1584.9,-423.1)).s().p("AAAKjQgdgVAGg2IDHBQQiwhihNhxQgGgJgUAAQAAgKACgKQAThSg9ACIgUigIighQIAAlnQCCh3g6j0QgLgugBgzIB4hQQC1gUCYBJQAQAHAKAUQAUAAANAJQAQAMALATIAACgIAwBXIAASsQi8gLiIhig");
	this.shape.setTransform(32.425,78.4183);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost19_mc, new cjs.Rectangle(0,0,64.9,156.9), null);


(lib.ghost18_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1497.4,-496.1)).s().p("AEXMSQgxhwgohoQgtgEgKglQgFgTAAgUIg8gUIgUg8Ig7gUQAAgUgGgSQgEgMgMgGQgIgEgKAAQgkgQgXgdQgVgagogJQgJgVgPgPQh6hwhyiXQgNgkglgWQgUgMgKgeIhQhQQgHhGgygIQgDgCAAgUIAAhkIBkhkIEOAAIAeg8QAAgoAQggQAEgIAUAAIAoigQBagBBWASQAoAHArAQQAUAUAYAFQA4AOA8ABIBQAoQAKAUANASQAHAMAKAKQBSAOAhAbQAlAeBEAdIA8B4QgLBDg/AaQgOAGgMAVQAAAegLAYQgKAXgkAMQgDABAAAKIAAB4IgoAoIgUNbIhQAUQg2gGgRgmg");
	this.shape.setTransform(65.025,83.0224);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost18_mc, new cjs.Rectangle(0,0,130.1,166.1), null);


(lib.ghost17_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1170.3,-325.1)).s().p("AFoOYIgog8Ih4goQiajui5i2IiMg8Qgag8g2gnIg8gpQgKgUABgUQABg+hIAWQgHhzhLhaQgXgdAZhVIB4gUQiWh0hVicQgFgIgUAAQgThSgMhjQgJhOAAhRQADglA5ARQBgAaAEhCQAKAAAKgDQBQgPAUA6QAUAAATAEQBXAVgGhBIEEgUICLBQIAUCgQBCBlgICMQgDA7BBAUIAoCgQAUAAAIAJQAXAfAJAoQBGBFBKBBQAjAfA9AiIAUAoQBDAAAfBIQAMAcAeAUQAAAUAGASQAKAeAsAgIAUH0QgUAAgCAHQgUAygmAXg");
	this.shape.setTransform(75.9988,92.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost17_mc, new cjs.Rectangle(0,0,152,184.1), null);


(lib.ghost16_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-920.3,-239)).s().p("AnzJEIgog8Ii0hQIAAigQAmghATgxQADgIAAgKQA5gcASgiQAFgIAAgKQA1gFAogZQARgKAKgUIA8gUIgUifQgeAAgVgOQgJgGAAgUIAAjIQAogBAngFQCLgWAqBEIDvgUQAUAAAFgJQA2hfBRhMQA0gXAfgHQAlgKAoAAIBQA8QCFB4BXCMIAAEDIg8BQIAAB4QAFAuAeAWQAhAZAgAbIAoBQIgUCMIjcAUIgog8IhQAAIhNg3IgIAIQhGA4hVBHg");
	this.shape.setTransform(72.025,58);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost16_mc, new cjs.Rectangle(0,0,144.1,116), null);


(lib.ghost15_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-948.3,-407)).s().p("AGjQhQAWgGASgLQgngCgkgKQgugPgmghQAAgJgEgCQgfgPgSgYQgHgKgUAAIgUg8QgKAAgJgDQglgKgEgvIhQAAQjfiiiIjGQgKgKgMgIQg6gqg8goIAAhQQgUgKAAgJQAEhWhAAFIAUjHIgohkIgUAAQhVAFgjgtQiFjXBaj2QADgJAAgKQAUAAAFgJQARgcASgXQBTgkBKhDQArgmAognQAUAAAPgIQAXgNACgnIAUAAQBEgGA0giIBkAAQAAgUAHgEQAggOApgCIAnhRIFoAUIBQA9IAUBkQBUDygRFmQgCA4A3gQIAoJrQAUAUAMAYQAVAsBDgIIAUF8Qg4BghpBTQgnAfg8ALQgQAYgZAPIAVAAIB4hQIi0CgQhNgtBMgSg");
	this.shape.setTransform(75.9459,112.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,151.9,224.1);


(lib.ghost14_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1083.8,-504.5)).s().p("AoCFaIAUh4QAAgUAJgFQAdgSARgVQAFgGAAgKQAJg8ARgkQAjhKA7gxIAojIIB5h4ICMAAIhvBGQBpgKBpAAQA3AyAyAhQAlAYBOgHQAKAUAOAQQA0A3BAAJQAAAeAMAXQBQCXggDXQgUAAgBAEQgGAogcALQgPAFgKAUQhuABhtANQiGAOiBAAQjsAAjegwg");
	this.shape.setTransform(51.4944,39.4277);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost14_mc, new cjs.Rectangle(0,0,103,78.9), null);


(lib.ghost13_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1067.3,-611.1)).s().p("AlUEOQgigfgjgnIAUlnIDIhkICMiMIFngUQBEArAKBLQACAMAUAKIgUFnIhkB4QgeAKgcANQgkAQguApQgoABgcARQgaAShBgQQgqgMACAgIBPAoIiLA8Qh1gphyhtg");
	this.shape.setTransform(41.025,42);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost13_mc, new cjs.Rectangle(0,0,82.1,84), null);


(lib.ghost12_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1323.9,-734.8)).s().p("ABBVAIgUg8Ig7gUIgUhQQgQgbgfgrQgug+gHhEQgUAAgOgKQgPgKgNgTQgIgLgKgKIBQAUIh4h4IgUhQIhQg8IgUhQQhXhkgYh6QgPhPg2ABQABiDhehKQgoghAMhRQAAgKgBgBQhEgKAdhjQiPmdBBnqQAOhoAsheQAAgKAFgHQAZgkAZgfQAFgGAAgKQH/g6DRG2IAABQQBZBAA2BQQApA9A4AjQCbD0BiDcQARAlAKAoQBKBwAsCTQAUBHAqBFIAUDcQBJEFgkEoQgVCoh0Bfg");
	this.shape.setTransform(81.4149,134.3859);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost12_mc, new cjs.Rectangle(0,0,162.8,268.8), null);


(lib.ghost11_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1154.7,-930.9)).s().p("AAGJZQgQg8hHgIQgLAAgKgKIgBgUQgBgmgXgNQgPgJgUAAIgokEIg8hQIg8gUQgUgegbgUQgNgKgUAAIgohPQhCAGgRg7QgriOAailID+gQQAWghAEgzIBQgUQgMhIBcAHQAoAGAogBQgMA9BIgRQATgEAUAAQAKAUAQALQAOAJAUAAIAUBQQDmDIBGC0IBQAoQAZBKgPBUQgGAkgYAZQgwAXgoAXQgeAQgWASIgoB4QAAAUgKAKQgKAKgUAAIgUBQQgKAAgKgCQg/gKADBJQAAgBgUAAIigAUQgKAAgBgCg");
	this.shape.setTransform(55.263,60.294);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost11_mc, new cjs.Rectangle(0,0,110.6,120.6), null);


(lib.ghost10_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-1062.5,-787.1)).s().p("AgpIwQgKgzgygLQgogIgogKQAAgUgKgKQgKgKgUAAQgBgogLgkQgchjhQgFIhkh4IgUg8Qhlhpg7hKIAUjwIBQhQIAAhQIBkhkIB4AAIL3AoQAUAeATAfQDYFmibHgIgoAoIgUBQIiMCMg");
	this.shape.setTransform(62.2464,60);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost10_mc, new cjs.Rectangle(0,0,124.5,120), null);


(lib.ghost09_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-894.3,-536.2)).s().p("AH0N5QjbgGi1giQgfg4g5gcQhVgphWgjQAAgUgGgSQgEgMgMgEQgSgGgUAAIgUhQQgKgUgQgLQgOgJgUAAIgUhQIgogoIAAjwQABiEgphXQiBgjhwhAQhgg2hThDIAAkYICggpIBQgnQAogLAigTQAkgVAegdIAUhQQAxgEAggjIAngqIErAAQAfAkBGAXQAoAMAnAKIBkDHQAUALATAMQALAIAKAKQAhBXACBIQALG7CuDtIBQDIQAUAAAKAKQAwAvAqBnIg8hkIAoBkIA8AUIAUB4IhkBkQhEAWhZAAQgeAAghgCg");
	this.shape.setTransform(82.025,89.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost09_mc, new cjs.Rectangle(0,0,164.1,178.3), null);


(lib.ghost08_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-948.2,-696.9)).s().p("ABlKWQAAgUgIgDQghgPgngCIhPigIAdAFQhThEgzhwQgfhFhAAEIgohkIAAg8QhUgUhUgtQg8ghg0gVQg9i4ANjtQAEhTBAgQQAKgKAIACQBKALgMg/QDPgxDpAFQBQACBPAWIAoBQQENCOBoEsQAHASAAAUQB3CAgpEPQgNBWgFBeQgYAkgdAMQgxATAWBJIh4A8g");
	this.shape.setTransform(62.9611,68.2266);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost08_mc, new cjs.Rectangle(0,0,125.9,136.5), null);


(lib.ghost07_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-785.3,-935)).s().p("ApJLjIgxgdQhshBh/hTIA8i1QAUABAKgKQAKgLAAgTIAoigIBQgpIAUizQAUgeAOggQA7iEBrhWQAKgoARglQAihJAnhGIBQgoIADgJQgIAJgjAAIA2gsIAGgQIACgBIAIgcQANgwAlgDIA0AAIAcgUIgZAUICkAAQBLAGAZA2IB4AUIAoA8QBVgHBFAuQBFAtAlBMIA8AUIBkDwIBkBRIAoB2QAABugJBuQgMCgh3A8IgUA9IhkAUIg8A8IhQAUQgKATgNASQgRAWgUAVIgGARg");
	this.shape.setTransform(87.025,73.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost07_mc, new cjs.Rectangle(0,0,174.1,147.8), null);


(lib.ghost06_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-730.9,-510.9)).s().p("AAiQmIjHhkIh4lAIgPgTIgGgHQi4jphzkZIg8gUQktr7IdmNQItgOIyA2IBQCMIgUKoQg8APAGBDQAEAwgKAzIhQBPIgUCMIiMCMIAABkQgUAeAAAeQABBAg9AQIgUFoIhQCMIl7AUg");
	this.shape.setTransform(77.3814,108.1809);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost06_mc, new cjs.Rectangle(0,0,154.8,216.4), null);


(lib.ghost05_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-565.5,-375.2)).s().p("AhdK/QgTgFgUAAIhQhQQgchmgxhPQgng+gEhNQg0ADglg5QgLgQgUgKQgPhEgWhBQgDgHgUAAIAAhjQhbiXAijkQAJg+Acg7ICgi0QGrhkEQFoQCrEPAdFIQBDBSgUCLQgHAxAAAyQg5AzghBVQgKAYgUAUQgKAKgIAAQhJgLALA9Ij/AAQgiAFgiAAQhEAAhFgUg");
	this.shape.setTransform(57.9042,72.3545);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost05_mc, new cjs.Rectangle(0,0,115.8,144.7), null);


(lib.ghost04_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-300.1,-384.1)).s().p("AjHOOIgoAAIglgrQgogvgrgKQArkPhkijQgXglAAgxQAAgUgIgQQgNgXgTgVQlDiBirjxQgGgJgUAAIAAjwICggoQDRimEPhyQCVAOBfguQAQgIAUAAQBEhbCWgMQABACAAgUIGkgUQBSA/A4ApQAWARAUAUQBOCrAqC9IA8A8IAoFUQAUAJALAQQAJAOAAAUIgUGQIg8AUQgsDRjsBvIgUA8ItbAUIDIAAQg+AphIAAIgagBg");
	this.shape.setTransform(100.025,91.0884);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost04_mc, new cjs.Rectangle(0,0,200.1,182.2), null);


(lib.ghost03_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-123.1,-445.9)).s().p("AhZMEQAAgUgKgIQgjgbgjgZIAAnMIhQhQQgXhXhQgxQgHgEgKAAQiUjtgMlCQCkiMDEhQQDqgPDgAmQApAHAoAKIAUBkIA8AUQBVChgFDbQgBAoABAoQgYBQgkAmQgUAWAAAnQAAAKgEAIQgUAmgQAsIgoC0Qg7AqgIBhQgEApgJAoIg8B4QgoBIh4ACQgyADgcgPIAmA6g");
	this.shape.setTransform(53.0139,77.2228);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,106.1,154.5);


(lib.ghost02_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-273.1,-680)).s().p("AnuIlIiHhNIAUAAIAOAJQgthOgjhQQgKgYAQhEQhdimAckRQAFgyAAgyIBQhQIAAhQIBQgoIAUg8QAKgKAMgCQArgMASgiQAHgMAKgKQAUAAATgEQAwgLgHgtIF7gUQAeAUAZAZQAPAPAKAUIBQAAQDAC/ChDcQAHAJAUAAIAUBQQAeAeAbAhQANARAKAUIDIDHIAUAUIAoAoIAADxQhtCyi/ACIg8AoIiMAAIgoAoQhyARhsAAQldAAkli0gArFHYQgig3hsgnQgSgGgUAAIgUg8IEYCgg");
	this.shape.setTransform(91.025,72.8887);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost02_mc, new cjs.Rectangle(0,0,182.1,145.8), null);


(lib.ghost01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-29.1,-770.1)).s().p("AhaIzQgvgbhLgUQgTgGgUAAIgnhgIAAtLQAfg0AogyIAlgrQAYgcAbgbQBZAAA5BLQANAPAUAKIAABQIAvA9IAHAIIAAAAIAHAJIBjBmIBIDzQAaCsgmC4QgKAUgQALQgOAJgUAAIgUBQIg8A8IgUA8IgMAJIAgALIgzAAIgeASQgTAMgUAKQhVgDgNhAg");
	this.shape.setTransform(29.0612,63);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-123.1,-735.5)).s().p("AgDgDIABAAIAGAIIgHgIg");
	this.shape_1.setTransform(39.625,25.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-92.2,-734.7)).s().p("AADAEIAAAAIgGgHIAHAHIgBAAg");
	this.shape_2.setTransform(38.9375,24.5125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ghost01, new cjs.Rectangle(0,0,58.2,126), null);


(lib.补间2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Volleyballgirlpng复制();
	this.instance.setTransform(-46.5,-134.7,0.3973,0.3973);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.5,-134.7,93,269.4);


(lib.Dumbell = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Dumbellpng复制2();
	this.instance.setTransform(-4,-5,0.4068,0.4068);

	this.instance_1 = new lib.face();
	this.instance_1.setTransform(91,76,0.3634,0.3634);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AKYPFQgJgGgEgLQAlgzAmgyIAAgEQAHgsAKgsQgDgXgLgPQhPhthWhlQgogcgegmQgegHgbgKQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAAAQgYgSgOgcQg6gngqgjQAJAOADARQhpAghJgxQgTABgMAHIgJAIQhWBEhKBNQhTAfhYgJIgPghQhBicAgihIgCAAQgCgGAAgGIgBgFQgCgJAHAAIAAgCQgHgBADgKIACAAQAChAAJg1QhQgKhAgZQhmgShfgZIAAgEQgEgOgJgIIgBADQgIAIgIAGIAAAEQAFAMAIAKIAAAFIANBwIgBAEQgBAFgCAEIACABQAFA1ABA4IADAAQAUAeAIAnIAAAEQgJAfgEAjIABADQAHAGgIAJIACAAQAJBfgHBuIACAAQADAYAAAYQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAdAXgCA3IgDAAQgCAHgIABQgKAKgMgKIgBgEQgFgPgLgLIgfAaQgjAPgaAYQhDALg8ACIAAgCQgLgEACgQQgNAUgRgCQAJgSgDgaIgBgEIADgCIAJgGIAAAmIgHAGIgCADQgBAFgDAEQAMgIAIgLQAKgMANgKQAKgJAIgLQAFAAADgCQATgJAagCIACgCQgXgEAVgDQAGgMAEgOIAHgWQAFgLAAgPIADgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIABgDIADgFIgsidQgVhJgEg2QAGgIgBgOIgBgWIAAAAIABgHIAAgJQABgDADgDIgDgEIgBgFQgDgUgHgVIAAgCIgBgBIgJgTQgJgQgKgPQgLg7gIhAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQgfhBgKhXQADgEAAgFQANiGAlhuQAQABACgOIgEgBQg+hLgwhFIAAAFIAAAAIgHgHIADgKIAAgBIAAgCIgBgBIgRgWIgBgOQgThdAYhaQABAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAQAFgOAGgMQgDgEAAgEIAAgIIAIgIQASgUAUgPIARgNIAEgEIAHgEQAMgEAMgHIgOABIACgDIAFgHIAlgDIAAgBIASAAIAHAAQAjAOA2AKIACAAQADACAEAAQACAKALABIACABIADABQANANASAIIADACIABADQAIAGAEAIIABAEIAAAEQAKABABAMIABABQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAIAFAEAIIABAEIAAAEQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAABIADACIADABIAAAEIAAAFIAAAEQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIACACIAEABQAiBLASBbIAAAFIAAAEQBnAABegdQAEgCADACIABADQA4gMA+gIIABAAQAEgCAEAAQCeAVB4A7IABABQAEACAEAAIABADIACACQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQARAGARAJIABAAQAEACAEAAIAEAFIABACQAEACAEAAIABADIADACIABAEQAIAAAEAFIACACIADABQAFALAMAEIACACIADABIAKAMIACACIABADQAIAFAEAJIACADIAEABQAjBAgaBDIgCADIgDABIAjAIIADACIABADIAMAKIACACQAEABAEAAQAEAKAIAFIACACIAEABQAFAKAHAIIACADIADABQADAMAJAHQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAEIAIAFIABAEIAAAEQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIACACIAEABQAXBHAgA9IABAEIAAAEIAEABIACACIADABQgDAMAHADIACACIADABQAEAJAGAHIACADIABADQAKAJAHANIAAAEIAAAEIAEABIACADIADABQgDAJAHACIABACIAAAEIADABIACACQAAABAAAAQABAAAAAAQABABAAAAQABAAAAAAIAIAZIACACQADACAFAAQAOBdAYBSIABAEIAAAFIADABIACACIAEABQACAXAKARIABAEIAAAEQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIACACIAEABQAAANAHAGIABADIAAAFQAIABABAHIABAEIADABIAKAHIACACQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQANAEAMAGIABABQAGACAHAAIABADIACACIABAEQAFAAADABIACABQADACAFAAIABADIACACQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAEAAAEABIACABQADACAFAAIABADIACADIABADQAMgBADAJIABACIABADQAKAEAFAIIACACIABADQAJAHAHAIIACACIAEABQAJAIAGANIABACIABADQAjAuARA/IABAFIAAAEQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIACACIADABIAhB2IABABIABAEQAKABABAMIABABIABADQAIAFAFAJIAAAEIAAAEIAIAFIABAEIAAAEIADABIADACIADABQABAOAHAJIACADIADABQACAEAEACIALAEIAAADQAJAIACASIABABQAAABABAAQAAAAAAABQAAAAAAAAQABABAAAAIAEgDIAIgDIABgCIAACug");
	this.shape.setTransform(173.4974,138.675);

	this.shape_1 = new cjs.Shape();
	var sprImg_shape_1 = cjs.SpriteSheetUtils.extractFrame(ss["Assignment_4_atlas_1"],0);
	sprImg_shape_1.onload = function(){
		this.shape_1.graphics.bf(sprImg_shape_1, null, new cjs.Matrix2D(0.394,0,0,0.394,-53.4,-111.6)).s().p("AoVRYQCSAACSACIAgABIlEABgAITsbIgHgBIgHgIIAFgOIAMAXIgDAAgAAsv3QgRgXgegEQgggEgUATQAAgNABgbQACgcgBgOIgBgGIDFAAIgbAUIg5ByQgFgUgKgOgAkSwyQgegDgUARIABgQQAAgWgCgRIB0AAIgEAMQgGATgGAlQgRgXgggEg")
	}.bind(this);
	this.shape_1.setTransform(53.4375,111.6);

	this.shape_2 = new cjs.Shape();
	var sprImg_shape_2 = cjs.SpriteSheetUtils.extractFrame(ss["Assignment_4_atlas_1"],0);
	sprImg_shape_2.onload = function(){
		this.shape_2.graphics.bf(sprImg_shape_2, null, new cjs.Matrix2D(0.437,0,0,0.437,-195.9,-0.1)).s().p("AueAAIgBAAIc/AAIAAABQuggBueAAg")
	}.bind(this);
	this.shape_2.setTransform(177.3,-11.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance,p:{scaleX:0.4068,scaleY:0.4068,x:-4,y:-5}}]}).to({state:[{t:this.instance,p:{scaleX:0.4239,scaleY:0.4239,x:-10,y:-15}}]},1).to({state:[{t:this.instance,p:{scaleX:0.3952,scaleY:0.3952,x:0,y:0}},{t:this.instance_1}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-15,280.2,250.2);


(lib.元件1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-797.9,-775.8)).s().p("AFSC4QAXg1AggwIAhAAQAAAKAEADQAfARAjALIhkAKIgKAxIgUAOgAnagjIgBAAQgagDAIgbIAAh5IAKgKQACAKAFAIQADAFAKAAQAAAEACAFQANAXAJAPQAGAHAKAFQAIAXANAUQAJANALAZIgZABQgkAAgfgDg");
	this.shape.setTransform(61.4559,80.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-789,-817.2)).s().p("AmzS/QgpgGgnABIgKhuIABAAIAngUIAAgCQABgOAHgIQAPgUARgaIALoJQAQgbAHghIAIhFIAAgPIgBgFIAAgCIAAgDIAAgBQABgiAcgLIAKhkIAVgeQAHhVAWhRQAAgDAKAAIAAiCQAIgRAEgTIAPh0IgBgrIgCgPIgBgQIgDhAIgIgTQgLgZgJgNQgNgVgIgWQgKgFgGgIQgJgOgOgYQgCgEAAgFQgKAAgCgEQgGgIgBgKIAAgIIgDgXIgEg+IARhwQARgxAhghQASgSAVgNQAFgKACgKQAEgUAHgQQADgEAJAAIAAgCIgCgOIgCgsIAGhCQAEgTAFgSQAJgbAoAKIA9gUIA7AUIALAoIAHALIA+hHQABgTAZgFQAVgFAqAJQAbgBAIAoQAEATACAWQBXBDAWBdIAKCgIA9AKIBQAyIBaB4IAKCqIATAeIgJBQIgNASQggAvgYA2IgBACIBZAnIgTgyIABAAQAaABADAhIABAKIAAAFIAAACQgCBNgnAgIh/AKIgEAKQhLCPgtDEQgODUgkDQIgTAeIgBAAQAFAQADAQIABAfIgHAuQgGAYgNAXQgXArgJAzIgVALQgJAKgEAMQgHAQAAASIAAACIAAACQgKAAgCAEQgIALgEANQgBACgEAAIgpAoIiUAUQgGAKgHAHQgVARgRAEQgFACgFAAQhGAlhoAAQgbAAgdgCg");
	this.shape_1.setTransform(52.6,121.6927);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件1, new cjs.Rectangle(0,0,111.1,243.4), null);


(lib.Arm_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Lowerarm();
	this.instance.setTransform(0,70.6,0.4556,0.4556,-59.9992);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Arm_mc, new cjs.Rectangle(0,0,85,96.1), null);


(lib.Swimmer = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.Swim1();
	this.instance.setTransform(116.4,98.5,1,1,0,0,0,116.4,98.5);

	this.instance_1 = new lib.Swim2();
	this.instance_1.setTransform(108,95.8,1,1,0,0,0,125,100.8);
	this.instance_1._off = true;

	this.instance_2 = new lib.Swim3();
	this.instance_2.setTransform(116.4,98.5,1,1,0,0,0,116.4,98.5);
	this.instance_2._off = true;

	this.instance_3 = new lib.Swim34();
	this.instance_3.setTransform(98.2,105.2,1,1,0,0,0,118.2,75.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_2}]},9).to({state:[{t:this.instance_3}]},9).wait(8));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,regX:125,regY:100.8,x:108,y:95.8},10).wait(26));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:false},10).to({_off:true,regX:116.4,regY:98.5,x:116.4,y:98.5},9).wait(17));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({_off:false},9).to({_off:true,regX:118.2,regY:75.2,x:98.2,y:105.2},9).wait(8));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20,-5,260.5,208);


(lib.元件2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.补间2("synched",0);
	this.instance.setTransform(46.5,134.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件2, new cjs.Rectangle(0,0,93,269.4), null);


(lib.Volleyball_girl_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.元件1();
	this.instance.setTransform(55.5,121.7,1,1,0,0,0,55.5,121.7);

	this.instance_1 = new lib.元件2();
	this.instance_1.setTransform(50.5,20.7,1,1,0,0,0,46.5,134.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},10).wait(6));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,regX:46.5,regY:134.7,x:50.5,y:20.7},10).wait(6));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.5,-114,115.6,357.4);


// stage content:
(lib.Assignment_4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		this.stop();
		
		this.winner_mc.visible = false;
		
		this.rotate_btn.addEventListener("click", rotate_btn.bind(this));
		
		function rotate_btn(){
			this.rotate_btn.rotation-=45;	
		}
		
		this.Scary_ghost.visible = false;
		
		this.Window_btn.addEventListener("click", ClickToHide.bind(this));
		
		function ClickToHide(){
			this.Scary_ghost.visible = true;
		}
		
		this.Volleyball_btn.addEventListener("pressmove", ClickToDrag.bind(this));
		
		function ClickToDrag(e) {
			var p = stage.globalToLocal(e.stageX, e.stageY);
			e.currentTarget.x = p.x;
			e.currentTarget.y = p.y;
		}
		
		var keepcount = 0;
		
		this.ghost01_mc.addEventListener("click",addOne.bind(this));
		this.ghost02_mc.addEventListener("click",addOne.bind(this));
		this.ghost03_mc.addEventListener("click",addOne.bind(this));
		this.ghost04_mc.addEventListener("click",addOne.bind(this));
		this.ghost05_mc.addEventListener("click",addOne.bind(this));
		this.ghost06_mc.addEventListener("click",addOne.bind(this));
		this.ghost07_mc.addEventListener("click",addOne.bind(this));
		this.ghost08_mc.addEventListener("click",addOne.bind(this));
		this.ghost09_mc.addEventListener("click",addOne.bind(this));
		this.ghost10_mc.addEventListener("click",addOne.bind(this));
		this.ghost11_mc.addEventListener("click",addOne.bind(this));
		this.ghost12_mc.addEventListener("click",addOne.bind(this));
		this.ghost13_mc.addEventListener("click",addOne.bind(this));
		this.ghost14_mc.addEventListener("click",addOne.bind(this));
		this.ghost15_mc.addEventListener("click",addOne.bind(this));
		this.ghost16_mc.addEventListener("click",addOne.bind(this));
		this.ghost17_mc.addEventListener("click",addOne.bind(this));
		this.ghost18_mc.addEventListener("click",addOne.bind(this));
		this.ghost19_mc.addEventListener("click",addOne.bind(this));
		this.ghost20_mc.addEventListener("click",addOne.bind(this));
		this.ghost21_mc.addEventListener("click",addOne.bind(this));
		this.ghost22_mc.addEventListener("click",addOne.bind(this));
		this.Scary_ghost.addEventListener("click",addOne.bind(this));
		this.rotate_btn.addEventListener("click",addOne.bind(this));
		
		
		function addOne(e){
			
			e.currentTarget.visible = false;
			
			if (keepcount == 23){ this.winner_mc.visible = true;
		
		
			}else{ 
				keepcount++;}
			
			this.showscore.text = keepcount;
		}
		
		if (this.Volleyball_btn.x >= 840){
		this.gotoAndPlay(Vgirl_mc);		
			}else{
				this.Vgirl_mc.gotoAndStop();		
			}
		
		//Enlarge
		this.Dumbell_btn.addEventListener("click", enlargeHead.bind(this));
		
		function enlargeHead(){
			this.Arm_mc.scaleX+=0.25 ;
			this.Arm_mc.scaleY+=0.25 ;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Winner
	this.winner_mc = new lib.winner_mc();
	this.winner_mc.name = "winner_mc";
	this.winner_mc.setTransform(968.2,546.15,1,1,0,0,0,996.2,586.1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().bs(img.Ghosts).ss(1,1,1).p("EibqhbkME3VAAAMAAAC3JMk3VAAAg");
	this.shape.setTransform(968.25,546.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.winner_mc}]}).wait(1));

	// Score_Pannel
	this.Score_btn = new lib.Score();
	this.Score_btn.name = "Score_btn";
	this.Score_btn.setTransform(1383.1,79.3,1,1,0,0,0,63.1,55.3);
	new cjs.ButtonHelper(this.Score_btn, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.Score_btn).wait(1));

	// Dumbell_arm
	this.Arm_mc = new lib.Arm_mc();
	this.Arm_mc.name = "Arm_mc";
	this.Arm_mc.setTransform(537.7,148.15,1,1,0,0,0,42.5,48.1);

	this.timeline.addTween(cjs.Tween.get(this.Arm_mc).wait(1));

	// Ghosts
	this.ghost22_mc = new lib.ghost22_mc();
	this.ghost22_mc.name = "ghost22_mc";
	this.ghost22_mc.setTransform(1645.5,55.5,1,1,0,0,0,55.1,52.5);

	this.ghost21_mc = new lib.ghost21_mc();
	this.ghost21_mc.name = "ghost21_mc";
	this.ghost21_mc.setTransform(946.25,152.05,1,1,0,0,0,70,52);

	this.ghost19_mc = new lib.ghost19_mc();
	this.ghost19_mc.name = "ghost19_mc";
	this.ghost19_mc.setTransform(1770.85,426.1,1,1,0,0,0,32.4,78.4);

	this.ghost18_mc = new lib.ghost18_mc();
	this.ghost18_mc.name = "ghost18_mc";
	this.ghost18_mc.setTransform(1683.4,499.1,1,1,0,0,0,65,83);

	this.ghost17_mc = new lib.ghost17_mc();
	this.ghost17_mc.name = "ghost17_mc";
	this.ghost17_mc.setTransform(1356.35,328.05,1,1,0,0,0,76,92);

	this.ghost16_mc = new lib.ghost16_mc();
	this.ghost16_mc.name = "ghost16_mc";
	this.ghost16_mc.setTransform(1106.25,242.05,1,1,0,0,0,72,58);

	this.ghost15_mc = new lib.ghost15_mc();
	this.ghost15_mc.name = "ghost15_mc";
	this.ghost15_mc.setTransform(1134.4,410,1,1,0,0,0,76,112);

	this.ghost14_mc = new lib.ghost14_mc();
	this.ghost14_mc.name = "ghost14_mc";
	this.ghost14_mc.setTransform(1269.8,507.45,1,1,0,0,0,51.5,39.4);

	this.ghost13_mc = new lib.ghost13_mc();
	this.ghost13_mc.name = "ghost13_mc";
	this.ghost13_mc.setTransform(1253.3,614.1,1,1,0,0,0,41,42);

	this.ghost12_mc = new lib.ghost12_mc();
	this.ghost12_mc.name = "ghost12_mc";
	this.ghost12_mc.setTransform(1509.9,737.7,1,1,0,0,0,81.4,134.3);

	this.ghost11_mc = new lib.ghost11_mc();
	this.ghost11_mc.name = "ghost11_mc";
	this.ghost11_mc.setTransform(1340.6,933.9,1,1,0,0,0,55.2,60.3);

	this.ghost10_mc = new lib.ghost10_mc();
	this.ghost10_mc.name = "ghost10_mc";
	this.ghost10_mc.setTransform(1248.5,790.15,1,1,0,0,0,62.2,60);

	this.ghost09_mc = new lib.ghost09_mc();
	this.ghost09_mc.name = "ghost09_mc";
	this.ghost09_mc.setTransform(1080.25,539.25,1,1,0,0,0,82,89.2);

	this.ghost08_mc = new lib.ghost08_mc();
	this.ghost08_mc.name = "ghost08_mc";
	this.ghost08_mc.setTransform(1134.25,699.9,1,1,0,0,0,63,68.2);

	this.instance = new lib.ghost07_mc();
	this.instance.setTransform(971.25,938.05,1,1,0,0,0,87,73.9);

	this.ghost06_mc = new lib.ghost06_mc();
	this.ghost06_mc.name = "ghost06_mc";
	this.ghost06_mc.setTransform(916.9,513.95,1,1,0,0,0,77.4,108.2);

	this.ghost05_mc = new lib.ghost05_mc();
	this.ghost05_mc.name = "ghost05_mc";
	this.ghost05_mc.setTransform(751.45,378.25,1,1,0,0,0,57.9,72.4);

	this.ghost04_mc = new lib.ghost04_mc();
	this.ghost04_mc.name = "ghost04_mc";
	this.ghost04_mc.setTransform(486.1,376.95,1,1,0,0,0,100,91.1);

	this.ghost03_mc = new lib.ghost03_mc();
	this.ghost03_mc.name = "ghost03_mc";
	this.ghost03_mc.setTransform(309.1,448.85,1,1,0,0,0,53,77.2);

	this.ghost02_mc = new lib.ghost02_mc();
	this.ghost02_mc.name = "ghost02_mc";
	this.ghost02_mc.setTransform(459.1,683,1,1,0,0,0,91,72.9);

	this.ghost01_mc = new lib.ghost01();
	this.ghost01_mc.name = "ghost01_mc";
	this.ghost01_mc.setTransform(245.3,773.15,1,1,0,0,0,29.1,63);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.Ghosts, null, new cjs.Matrix2D(0.402,0,0,0.359,-36.2,-770.2)).s().p("AjGKUIighQIgDgVIAAiRIAnBgQATAAATAFQBMAVAuAaQAOBABWAEQAUgKATgMIAdgSIAzAAIgggMIAMgIIAUg8IA8g8IAUhQQAUAAAOgJQAQgLAKgUQBBk8h9kbQhLg/hUh1IAAhQQgUgKgNgQQg7hKhYAAQhhBgg+BnIAAi7QAtgVA6gXICNAUIAnA8IA9AUIAmA8IA8AUIAABRQAVAAAIAKQBCBKAuCPQA7A8AVCEQA2gJACBFQADBkABBlIhkCgIg8AoIgUBQQhMAOg+AjQhcA1hxAAIglgCg");
	this.shape_1.setTransform(252.4,773.1704);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.ghost01_mc},{t:this.ghost02_mc},{t:this.ghost03_mc},{t:this.ghost04_mc},{t:this.ghost05_mc},{t:this.ghost06_mc},{t:this.instance},{t:this.ghost08_mc},{t:this.ghost09_mc},{t:this.ghost10_mc},{t:this.ghost11_mc},{t:this.ghost12_mc},{t:this.ghost13_mc},{t:this.ghost14_mc},{t:this.ghost15_mc},{t:this.ghost16_mc},{t:this.ghost17_mc},{t:this.ghost18_mc},{t:this.ghost19_mc},{t:this.ghost21_mc},{t:this.ghost22_mc}]}).wait(1));

	// Volleyball
	this.Volleyball_btn = new lib.Volleyball();
	this.Volleyball_btn.name = "Volleyball_btn";
	this.Volleyball_btn.setTransform(758.8,552.7,1,1,0,0,0,23.2,17.9);
	new cjs.ButtonHelper(this.Volleyball_btn, 0, 1, 2, false, new lib.Volleyball(), 3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.People, null, new cjs.Matrix2D(0.398,0,0,0.359,-624.3,-555.2)).s().p("AgEALIABAAIANgjIgDAcIgKAHIgGAOQAAgKAFgEg");
	this.shape_2.setTransform(735.1,539.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.Volleyball_btn}]}).wait(1));

	// Swimmer
	this.instance_1 = new lib.Swimmer();
	this.instance_1.setTransform(267.35,813.8,1,1,0,0,0,116.4,98.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Dumbellman
	this.Dumbell_btn = new lib.Dumbell();
	this.Dumbell_btn.name = "Dumbell_btn";
	this.Dumbell_btn.setTransform(504.3,131.6,1,1,0,0,0,130.3,111.6);
	new cjs.ButtonHelper(this.Dumbell_btn, 0, 1, 2, false, new lib.Dumbell(), 3);

	this.timeline.addTween(cjs.Tween.get(this.Dumbell_btn).wait(1));

	// Scary_Ghost
	this.Scary_ghost = new lib.Scaryghost_1();
	this.Scary_ghost.name = "Scary_ghost";
	this.Scary_ghost.setTransform(1409.65,200.25,0.4268,0.4268,14.998,0,0,69.1,75.6);

	this.timeline.addTween(cjs.Tween.get(this.Scary_ghost).wait(1));

	// Window_btn
	this.Window_btn = new lib.Window();
	this.Window_btn.name = "Window_btn";
	this.Window_btn.setTransform(1375,185.9,1,1,0,0,0,82.8,82.9);
	new cjs.ButtonHelper(this.Window_btn, 0, 1, 2, false, new lib.Window(), 3);

	this.timeline.addTween(cjs.Tween.get(this.Window_btn).wait(1));

	// Rotating_Ghost
	this.rotate_btn = new lib.rotate_btn();
	this.rotate_btn.name = "rotate_btn";
	this.rotate_btn.setTransform(1512.1,156.5,1,1,0,0,0,43.1,53.5);
	new cjs.ButtonHelper(this.rotate_btn, 0, 1, 2, false, new lib.rotate_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.rotate_btn).wait(1));

	// People
	this.Vgirl_mc = new lib.Volleyball_girl_mc();
	this.Vgirl_mc.name = "Vgirl_mc";
	this.Vgirl_mc.setTransform(924.65,817.45,1,1,0,0,0,55.5,121.7);

	this.instance_2 = new lib.CachedBmp_1();
	this.instance_2.setTransform(132.75,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.Vgirl_mc}]}).wait(1));

	// BG
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.bf(img.Background, null, new cjs.Matrix2D(0.398,0,0,0.359,-835.6,-538.6)).s().p("EiCjBUKMAAAioTMEFHAAAMAAACoTgEg1ggtMQBPAABUgLIABAAIAHgBIACAAIAFgBQAPgBAPgFIAAgKIAAgCQAAgbAegLQAEg0AagmIAUgfQAFgcAAgaQAAhFghg6QgKgRgCgWIgegKIgKgoQg8gjgcg4QgCgEAAgFIgegKQgIgkglgeQgFgEAAgKIgegKIgBgKQgEgfgZgJIgKgpIgegdQgFgVgIgTQgHgQgKgPQAAgKABgJIABgJQAAgVgWgLQAFgSAAgQQAAgUgJgOQgNgagXgQIAAg8QhRhygyicIgegUQhFh9hbh0QkCjPkliZIgUgeQj8hdjkh1Qg/gahEgPQg5gqhTgHIgKAAIgegVIjIAAQgTASgVANIgeATIi/AKIgegdIhkAAQgaASgcANQgXAMgDAbQgTALgBAmIAAACQAAAaALATIgBAEIABgEQgLgTAAgaIAAgCQABgmATgLQADgbAXgMQAcgNAagSIBkAAIAeAdIC/gKIAegTQAVgNATgSIDIAAIAeAVIAKAAQBTAHA5AqQBEAPA/AaQDkB1D8BdIAUAeQElCZECDPQBbB0BFB9IAeAUQAyCcBRByIAAA8QAXAQANAaQAJAOAAAUQAAAQgFASQAWALAAAVIgBAJQgBAJAAAKQAKAPAHAQQAIATAFAVIAeAdIAKApQAZAJAEAfIABAKIAeAKQAAAKAFAEQAlAeAIAkIAeAKQAAAFACAEQAcA4A8AjIAKAoIAeAKQACAWAKARQAhA6AABFQAAAagFAcIgUAfQgaAmgEA0QgeALAAAbIAAACIAAAKQgPAFgPABIgFABIgCAAIgHABIgBAAQhUALhPAAIAAAAIAAAAQjkgBi5hYIgyAAIh4hlQjmAajnAsIgeAUIiCALIgeAUIgUAAIgEAAQhVAOhNAAIAAAAIAAAAQiIAAhwgqIgDgBIgBAAIgDgCQgBgbgKgdQgbhLggg7IAAgKQgDhBgbgtIgygUIAAgBQADgUgRgBIgBAAIAAAAQgGAAgJADIgUgVIgIAAIAAAAIAAAAQgOAAgOACIAAAAIgCABIgCAAIgCAAIAAAAIgBAAIgVACIAAAAIAAAAQgnAAgXgVIAAAAIgDgDIgBgBIhQAAQgFgKgIgFQg4gfgzgOQgFgKgIgIQghgfgJglQhJkqgNkpIgKgoIh4hkIAAgoIgHAAIAAAAIAAAAQgXAAAAgeIAAgBQAAgJgKgLIAAg8QgdgHgBggQAAgKgKgKIAKoAIAegdIgeAdIgKIAQAKAKAAAKQABAgAdAHIAAA8QAKALAAAJIAAABQAAAeAXAAIAAAAIAAAAIAHAAIAAAoIB4BkIAKAoQANEpBJEqQAJAlAhAfQAIAIAFAKQAzAOA4AfQAIAFAFAKIBQAAIABABIADADIAAAAQAXAVAnAAIAAAAIAAAAIAVgCIABAAIAAAAIACAAIACAAIACgBIAAAAQAOgCAOAAIAAAAIAAAAIAIAAIAUAVQAJgDAGAAIAAAAIABAAQARABgDAUIAAABIAyAUQAbAtADBBIAAAKQAgA7AbBLQAKAdABAbIADACIABAAIADABQBwAqCIAAIAAAAIAAAAQBNAABVgOIAEAAIAUAAIAegUICCgLIAegUQDngsDmgaIB4BlIAyAAQC5BYDkABIAAAAIAAAAg");
	this.shape_3.setTransform(967.625,538.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(931,499.1,1034.5,634.1999999999999);
// library properties:
lib.properties = {
	id: 'CC7E560D75641C4D931905ED401D4278',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/CachedBmp_1.png?1682305694053", id:"CachedBmp_1"},
		{src:"images/Background.png?1682305694053", id:"Background"},
		{src:"images/Ghosts.png?1682305694053", id:"Ghosts"},
		{src:"images/People.png?1682305694053", id:"People"},
		{src:"images/Assignment_4_atlas_1.png?1682305693866", id:"Assignment_4_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7E560D75641C4D931905ED401D4278'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;